const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

const copy = {
  en: {
    kicker:"A raw milk history game",title:"Return Dolly to Pasture",subtitle:"Guide Dolly out of the industrial city and back to green pasture. Every answer brings her closer to home.",journey:"Dolly’s journey",city:"Industrial city",pasture:"Pasture",chapter:"Chapter",stage1:"Milk Through History",stage2:"The Industrial City",stage3:"Return to Pasture",position:"Position",grass:"Grass earned",facts:"Facts discovered",how:"How to play",yourTurn:"Your turn",spin:"Spin to move",spinKicker:"THE JOURNEY CONTINUES",spinTitle:"Let’s see how far Dolly trots",spinning:"Spinning…",historyFact:"History fact",continue:"Continue the journey",quickGuide:"QUICK GUIDE",howTitle:"Help Dolly find her way home",rule1Title:"Spin the wheel",rule1:"Move 1–3 spaces along the trail.",rule2Title:"Discover the story",rule2:"Answer a new history question after every turn.",rule3Title:"Grow the pasture",rule3:"Correct answers earn grass. A wrong answer sends Dolly back one space.",homeKicker:"WELCOME HOME, DOLLY",won:"Dolly is back where cows belong.",wonCopy:"You explored the history of raw milk and helped return Dolly to green pasture.",correct:"Correct",turns:"Turns",closeGame:"Close game",question:"Question",of:"of",correctTitle:"That’s right!",wrongTitle:"Not quite — keep learning!",correctLead:"Dolly found a fresh patch of grass.",wrongLead:"Dolly steps back one space, but now you know the answer.",spaces:"spaces",space:"space",rolled:"Dolly can trot",mute:"Mute sound",unmute:"Turn sound on",start:"Start: The city",finish:"Home: Green pasture"},
  es: {
    kicker:"Un juego sobre la historia de la leche cruda",title:"Devuelve la vaca al pasto",subtitle:"Guía a Dolly fuera de la ciudad industrial y de regreso al pasto verde. Cada respuesta la acerca a casa.",journey:"El viaje de Dolly",city:"Ciudad industrial",pasture:"Pastizal",chapter:"Capítulo",stage1:"La leche en la historia",stage2:"La ciudad industrial",stage3:"Regreso al pasto",position:"Posición",grass:"Pasto ganado",facts:"Datos descubiertos",how:"Cómo jugar",yourTurn:"Tu turno",spin:"Gira para avanzar",spinKicker:"EL VIAJE CONTINÚA",spinTitle:"Veamos cuánto trota Dolly",spinning:"Girando…",historyFact:"Dato histórico",continue:"Continuar el viaje",quickGuide:"GUÍA RÁPIDA",howTitle:"Ayuda a Dolly a encontrar su hogar",rule1Title:"Gira la ruleta",rule1:"Avanza de 1 a 3 espacios por el sendero.",rule2Title:"Descubre la historia",rule2:"Responde una nueva pregunta después de cada turno.",rule3Title:"Haz crecer el pasto",rule3:"Las respuestas correctas ganan pasto. Una incorrecta hace retroceder a Dolly un espacio.",homeKicker:"BIENVENIDA A CASA, DOLLY",won:"Dolly volvió al lugar al que pertenecen las vacas.",wonCopy:"Exploraste la historia de la leche cruda y ayudaste a Dolly a regresar al pasto verde.",correct:"Correctas",turns:"Turnos",closeGame:"Cerrar juego",question:"Pregunta",of:"de",correctTitle:"¡Así es!",wrongTitle:"No exactamente — ¡sigamos aprendiendo!",correctLead:"Dolly encontró un nuevo pedacito de pasto.",wrongLead:"Dolly retrocede un espacio, pero ahora ya conoces la respuesta.",spaces:"espacios",space:"espacio",rolled:"Dolly puede trotar",mute:"Silenciar",unmute:"Activar sonido",start:"Inicio: La ciudad",finish:"Hogar: Pastizal verde"}
};

copy.en.rule1="Move 1–6 spaces along the trail.";
copy.es.rule1="Avanza de 1 a 6 espacios por el sendero.";
copy.en.playAgain="Play again";
copy.es.playAgain="Volver a jugar";

const questions = [
  {stage:0,en:["There’s evidence that humans have consumed raw milk for…",["At least 10,000 years","Since the time of the dinosaurs","Since Redmond started its dairy in 2003"],0,"Archaeological evidence traces human dairy consumption back at least 10,000 years."],es:["Hay evidencia de que los humanos han consumido leche cruda durante…",["Al menos 10,000 años","Desde la época de los dinosaurios","Desde que Redmond inició su lechería en 2003"],0,"La evidencia arqueológica remonta el consumo humano de lácteos al menos 10,000 años."]},
  {stage:0,en:["Families used to keep their own cows…",["On pastures","In cages ","In their houses"],0,"For much of history, family cows lived outdoors on pasture close to home."],es:["Las familias solían mantener sus propias vacas…",["En pastizales","En jaulas","Dentro de sus casas"],0,"Durante gran parte de la historia, las vacas familiares vivían al aire libre, en pastizales cerca de casa."]},
  {stage:1,en:["When cows were relocated to cities during the Industrial Revolution, they were kept in…",["Cramped, dirty quarters.","Offices","City parks"],0,"Urban dairy cows were often confined in crowded, unsanitary conditions."],es:["Cuando las vacas fueron trasladadas a las ciudades durante la Revolución Industrial, se mantenían en…",["Espacios estrechos y sucios","Oficinas","Parques urbanos"],0,"Las vacas lecheras urbanas solían estar confinadas en condiciones hacinadas e insalubres."]},
  {stage:1,en:["The unhealthy milk produced by unhealthy city cows in the Industrial Revolution was called…",["Swill milk","Garbage milk","Blue milk"],0,"The notorious product became known as “swill milk.”"],es:["La leche insalubre producida por vacas urbanas enfermas se llamaba…",["Swill milk","Leche basura","Leche azul"],0,"Este producto de mala fama llegó a conocerse como “swill milk”."]},
  {stage:1,en:["People used to add _________ to swill milk to make it more palatable, creamy, and white.",["Molasses, eggs and starch, Plaster of Paris","Stevia, glue, white paint","Cane sugar, cream of tartar, bleach"],0,"Adulterants masked the milk’s poor color, texture, and taste without making it healthy."],es:["¿Qué se añadía al swill milk para hacerlo más agradable, cremoso y blanco?",["Melaza, huevos y almidón, y yeso de París","Stevia, pegamento y pintura blanca","Azúcar de caña, cremor tártaro y blanqueador"],0,"Estos adulterantes ocultaban el mal color, textura y sabor de la leche, pero no la hacían saludable."]},
  {stage:1,en:["A study by the New York Academy of Medicine later confirmed that a sharp rise in infant deaths (20% in a 4-year period) was linked to the contaminated \"swill milk\" produced by unhealthy cows in the Industrial Revolution.",["True","False"],0,"The New York Academy of Medicine connected the sharp increase in infant deaths to contaminated swill milk."],es:["Un estudio relacionó un aumento del 20% en muertes infantiles durante cuatro años con el swill milk contaminado.",["Verdadero","Falso"],0,"La Academia de Medicina de Nueva York relacionó el fuerte aumento de muertes infantiles con el swill milk contaminado."]},
  {stage:1,en:["Pasteurization is defined as…",["Heating milk to just below boiling for a specific period to kill harmful bacteria.","Stirring milk to harmful pathogens with centrifugal force.","Emulsifying milk to create a uniform texture."],0,"Pasteurization uses controlled heat and time to reduce harmful bacteria."],es:["La pasteurización se define como…",["Calentar la leche justo por debajo del punto de ebullición durante un periodo específico para eliminar bacterias dañinas","Agitar la leche para eliminar patógenos con fuerza centrífuga","Emulsionar la leche para crear una textura uniforme"],0,"La pasteurización utiliza calor y tiempo controlados para reducir las bacterias dañinas."]},
  {stage:1,en:["The main problem with pasteurization is that…",["It kills beneficial bacteria and enzymes as well as harmful pathogens","It renders milk unsuitable for making butter or cheese.","It changes the color and texture of the milk."],0,"Heat does not distinguish between harmful microbes and beneficial bacteria and enzymes."],es:["El principal problema de la pasteurización es que…",["Elimina bacterias y enzimas beneficiosas junto con los patógenos dañinos","Hace que la leche no sirva para mantequilla o queso","Cambia el color y la textura de la leche"],0,"El calor no distingue entre microbios dañinos y bacterias y enzimas beneficiosas."]},
  {stage:1,en:["In the Industrial Revolution, city cows were fed…",["Spent grain from alcohol production in local distilleries.","Fresh grass shipped in from the countryside. ","Leftovers from nearby restaurants. "],0,"Cheap spent distillery grain replaced the fresh pasture cows naturally ate."],es:["Durante la Revolución Industrial, las vacas urbanas eran alimentadas con…",["Grano usado de la producción de alcohol en destilerías locales","Pasto fresco enviado desde el campo","Sobras de restaurantes cercanos"],0,"El grano barato y usado de las destilerías reemplazó el pasto fresco que las vacas comían naturalmente."]},
  {stage:1,en:["Pasteurization was introduced to…",["Make swill milk taste better.","Kill harmful bacteria in dirty swill milk.","Make swill milk easier to make into ice cream."],1,"Pasteurization addressed dangerous pathogens in a deeply unsanitary milk system."],es:["La pasteurización se introdujo para…",["Mejorar el sabor del swill milk","Eliminar bacterias dañinas del swill milk sucio","Facilitar la elaboración de helado con swill milk"],1,"La pasteurización combatió los patógenos peligrosos de un sistema lechero profundamente insalubre."]},
  {stage:1,en:["The sale of raw milk was made illegal in order to…",["Make swill milk relatively safe and drinkable.","Promote the sale of non-dairy milks.","Encourage people to buy their own cows."],0,"Requiring heat treatment made contaminated industrial milk relatively safer to drink."],es:["La venta de leche cruda se hizo ilegal para…",["Hacer que el swill milk fuera relativamente seguro y bebible","Promover leches no lácteas","Animar a la gente a comprar sus propias vacas"],0,"Exigir tratamiento térmico hizo que la leche industrial contaminada fuera relativamente más segura."]},
  {stage:2,en:["To be able to sell raw milk in our brick and mortar stores, Redmond Farms had to…",["Work to propose a bill to allow to Utah legislature for the sale of raw milk.","Break into the state offices and rewrite the laws.","Keep cows in the stores."],0,"Redmond worked through the legislative process to make in-store raw milk sales legal."],es:["Para vender leche cruda en sus tiendas físicas, Redmond Farms tuvo que…",["Proponer un proyecto de ley ante la legislatura de Utah para permitir su venta","Entrar a las oficinas estatales y reescribir las leyes","Mantener vacas dentro de las tiendas"],0,"Redmond trabajó mediante el proceso legislativo para legalizar la venta de leche cruda en tiendas."]},
  {stage:2,en:["Redmond opened its dairy farm in____, but wasn’t able to sell its raw milk in stores until _____.",["2003, 2007","2001, 2020","1995, 2013"],0,"Four years of work separated the dairy’s opening from legal in-store sales."],es:["Redmond abrió su granja lechera en ____, pero no pudo vender leche cruda en tiendas hasta ____.",["2003, 2007","2001, 2020","1995, 2013"],0,"Cuatro años de trabajo separaron la apertura de la lechería de la venta legal en tiendas."]},
  {stage:2,en:["Redmond’s first attempt to legalize the sale of raw milk failed because…",["Many dairy groups in Utah opposed the law change. ","The Utah legislature didn’t like the taste of raw milk.","Redmond Farms didn’t live up to the state’s cleanliness standards."],0,"Opposition from established dairy groups stopped the first attempt."],es:["El primer intento de Redmond por legalizar la venta de leche cruda fracasó porque…",["Muchos grupos lecheros de Utah se opusieron al cambio de ley","A la legislatura no le gustó el sabor","Redmond no cumplió los estándares estatales de limpieza"],0,"La oposición de grupos lecheros establecidos detuvo el primer intento."]},
  {stage:2,en:["Back in 2003, Redmond was not able to sell raw milk because…",["Raw milk could only be sold by licensed dairies, at their actual farm. ","The sale of raw milk was totally banned statewide.","There was no market for raw milk in Utah."],0,"Utah law restricted sales to licensed dairies at the farm itself."],es:["En 2003, Redmond no podía vender leche cruda porque…",["Solo podía venderse por lecherías autorizadas en la propia granja","Estaba totalmente prohibida en todo el estado","No había mercado para leche cruda en Utah"],0,"La ley de Utah restringía la venta a lecherías autorizadas en la propia granja."]},
  {stage:2,en:["Redmond’s dairy farm first started as…",["A single cow owned by a neighbor (and future Redmond associate).","A cow that escaped a conventional dairy wandered onto the salt mine property.","A cow a Redmond associate rescued from a local petting zoo."],0,"The dairy story began simply, with one neighbor’s cow."],es:["La granja lechera de Redmond comenzó como…",["Una sola vaca de un vecino y futuro asociado de Redmond","Una vaca que llegó a la propiedad de la mina de sal","Una vaca rescatada de un zoológico infantil"],0,"La historia de la lechería comenzó de forma sencilla, con la vaca de un vecino."]},
  {stage:2,en:["Redmond’s dairy farm first served…",["Redmond associates. ","The town of Redmond.","Raw milk enthusiasts just over the state border."],0,"The first people served by the dairy were Redmond associates."],es:["La granja lechera de Redmond sirvió primero a…",["Los asociados de Redmond","El pueblo de Redmond","Aficionados a la leche cruda al otro lado de la frontera estatal"],0,"Las primeras personas atendidas por la lechería fueron los asociados de Redmond."]},
  {stage:2,en:["The argument that won over the legislature and led to the legalization of raw milk sales was…",["“We sell Coke and tobacco, and they cause known health problems. Redmond is trying to sell a nourishing, health-promoting product, though it does carry some risk.”","“Utah eats more ice cream than any other state, and raw milk is best for ice-cream making.”","“Raw milk will be the next big player in the Utah economy.”"],0,"The successful argument centered on informed choice and a nourishing product—not a claim of zero risk."],es:["¿Qué argumento finalmente convenció a la legislatura?",["Vendemos Coca-Cola y tabaco pese a sus riesgos conocidos; este es un producto nutritivo que también conlleva cierto riesgo","Utah consume más helado que cualquier otro estado","La leche cruda será el próximo gran motor de la economía de Utah"],0,"El argumento exitoso se centró en la elección informada y un producto nutritivo, no en afirmar que no tenía riesgos."]}
];

const state={position:1,turns:0,grass:0,correct:0,questionIndex:0,busy:false,muted:false,lang:"en",facing:"right",roll:1};
let tileMap=new Map(),rotation=0,audioContext=null,toastTimer=null,cowToken=null;
const els={board:$("#board"),scene:$("#scene"),spin:$("#spin-button"),backdrop:$("#backdrop"),spinnerModal:$("#spinner-modal"),questionModal:$("#question-modal"),rulesModal:$("#rules-modal"),finishModal:$("#finish-modal"),wheel:$("#wheel"),rollCopy:$("#roll-copy"),answers:$("#answers"),feedback:$("#feedback"),continue:$("#continue-button")};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const tr=key=>copy[state.lang][key]||key;
function shuffledAnswers(answers){
  const shuffled=answers.map((text,originalIndex)=>({text,originalIndex}));
  for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}
  return shuffled;
}

function pathColumns(){return innerWidth<=560?4:innerWidth<=850?6:8}
function physicalOrder(cols){const result=[];for(let row=0;row<24/cols;row++){const start=row*cols+1;const numbers=Array.from({length:cols},(_,i)=>start+i);result.push(...(row%2?numbers.reverse():numbers))}return result}
function drawTrail(){
  const svg=els.board.querySelector(".trail-svg");if(!svg)return;
  const boardRect=els.board.getBoundingClientRect();
  const points=Array.from({length:24},(_,i)=>{const rect=tileMap.get(i+1).getBoundingClientRect();return{x:rect.left-boardRect.left+rect.width/2,y:rect.top-boardRect.top+rect.height/2}});
  let d=`M ${points[0].x} ${points[0].y}`;
  for(let i=1;i<points.length-1;i++){const next=points[i+1],mid={x:(points[i].x+next.x)/2,y:(points[i].y+next.y)/2};d+=` Q ${points[i].x} ${points[i].y} ${mid.x} ${mid.y}`}
  d+=` Q ${points.at(-1).x} ${points.at(-1).y} ${points.at(-1).x} ${points.at(-1).y}`;
  svg.setAttribute("viewBox",`0 0 ${boardRect.width} ${boardRect.height}`);
  svg.querySelectorAll("path").forEach(path=>path.setAttribute("d",d));
}
function buildBoard(){
  els.board.innerHTML='<svg class="trail-svg" aria-hidden="true" preserveAspectRatio="none"><path class="trail-shadow"/><path class="trail-base"/><path class="trail-inlay"/><path class="trail-highlight"/></svg>';tileMap=new Map();const cols=pathColumns();const order=physicalOrder(cols);els.board.classList.remove("map-layout");
  order.forEach((number,index)=>{const tile=document.createElement("div");const row=Math.floor(index/cols);const isTurn=number!==24&&number%cols===0;const gateway=[9,17].includes(number);const zone=number<9?"city":number<17?"country":"pasture";tile.className=`tile zone-${zone} ${[4,9,14,19].includes(number)?"special":"fact"}${isTurn?" turn":""}${number===24?" end":""}${gateway?" gateway":""}`;tile.dataset.number=number;tile.innerHTML=`<span class="tile-number">${number}</span>${[4,9,14,19].includes(number)?'<span class="tile-icon">♧</span>':""}${gateway?`<span class="gateway-flag">${tr(number===9?"stage2":"stage3")}</span>`:""}`;if(number===1)tile.insertAdjacentHTML("beforeend",`<span class="start-label">${tr("start")}</span>`);if(number===24)tile.insertAdjacentHTML("beforeend",`<span class="finish-label">${tr("finish")}</span>`);els.board.append(tile);tileMap.set(number,tile)});updateBoard();requestAnimationFrame(drawTrail)
}
function stageForPosition(pos){return pos<9?0:pos<17?1:2}
function updateBoard(){
  tileMap.forEach((tile,n)=>{tile.classList.toggle("passed",n<state.position);tile.classList.toggle("current",n===state.position)});
  const pct=Math.round((state.position-1)/23*100);$("#progress-percent").textContent=`${pct}%`;$("#progress-fill").style.width=`${pct}%`;$("#position").textContent=state.position;$("#grass-count").textContent=state.grass;$("#facts-count").textContent=state.questionIndex;
  const completed=state.position>=24;els.spin.classList.toggle("hidden",completed);$("#replay-button").classList.toggle("hidden",!completed);
  const stage=stageForPosition(state.position);els.scene.className=`scene stage-${stage}`;$$('.chapter').forEach((c,i)=>c.classList.toggle("active",i===stage));
}
function addTrailEffect(){
  if(!cowToken)return;const sceneRect=els.scene.getBoundingClientRect(),cowRect=cowToken.getBoundingClientRect();const x=cowRect.left-sceneRect.left+cowRect.width/2,y=cowRect.bottom-sceneRect.top-7;const dust=document.createElement("span"),hoof=document.createElement("span");dust.className="dust-puff";hoof.className="hoofprint";dust.style.left=`${x+(Math.random()-.5)*22}px`;dust.style.top=`${y}px`;hoof.style.left=`${x+(Math.random()-.5)*18}px`;hoof.style.top=`${y+4}px`;hoof.style.setProperty("--hoof-rotate",`${state.facing==="left"?-18:18}deg`);els.scene.append(dust,hoof);setTimeout(()=>dust.remove(),800);setTimeout(()=>hoof.remove(),4100)
}
function growGrass(){
  const tile=tileMap.get(state.position);if(!tile)return;const tileRect=tile.getBoundingClientRect(),sceneRect=els.scene.getBoundingClientRect();for(let i=0;i<3;i++){const sprout=document.createElement("span");sprout.className="grass-sprout";sprout.textContent="♧";sprout.style.left=`${tileRect.left-sceneRect.left+tileRect.width/2-30+i*30}px`;sprout.style.top=`${tileRect.bottom-sceneRect.top-12+Math.random()*8}px`;sprout.style.animationDelay=`${i*.09}s`;els.scene.append(sprout);setTimeout(()=>sprout.remove(),1800)}}
function reactCow(type){window.Ruby3D?.setAction(type,type==="arrived"?1900:1200);if(!cowToken)return;cowToken.classList.remove("celebrate","sad","arrived");void cowToken.offsetWidth;cowToken.classList.add(type);setTimeout(()=>cowToken?.classList.remove(type),type==="arrived"?1900:1200)}
function openModal(el){els.backdrop.classList.remove("hidden");el.classList.remove("hidden")}
function closeModal(el){el.classList.add("hidden");if($$(".modal:not(.hidden)").length===0)els.backdrop.classList.add("hidden")}
function playTone(kind="step"){
  if(state.muted)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioContext ||= new AC();const now=audioContext.currentTime;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=kind==="good"?"sine":"triangle";o.frequency.setValueAtTime(kind==="good"?520:kind==="bad"?190:280,now);if(kind==="good")o.frequency.exponentialRampToValueAtTime(760,now+.2);if(kind==="bad")o.frequency.exponentialRampToValueAtTime(120,now+.25);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.07,now+.02);g.gain.exponentialRampToValueAtTime(.0001,now+.3);o.connect(g).connect(audioContext.destination);o.start();o.stop(now+.32)
}
async function animateMove(steps){
  const dir=Math.sign(steps);window.Ruby3D?.setMoving(true);cowToken?.classList.add("walking");for(let i=0;i<Math.abs(steps);i++){const old=state.position;state.position=Math.max(1,Math.min(24,state.position+dir));const cols=pathColumns();const oldRow=Math.floor((old-1)/cols),newRow=Math.floor((state.position-1)/cols);if(oldRow!==newRow)state.facing=state.facing==="right"?"left":"right";updateBoard();playTone();await wait(matchMedia("(prefers-reduced-motion: reduce)").matches?50:440);addTrailEffect();await wait(matchMedia("(prefers-reduced-motion: reduce)").matches?20:660)}cowToken?.classList.remove("walking");window.Ruby3D?.setMoving(false)
}
function spinResult(){return Math.floor(Math.random()*6)+1}
async function takeTurn(){
  if(state.busy)return;state.busy=true;els.spin.disabled=true;state.roll=spinResult();els.rollCopy.textContent=tr("spinning");openModal(els.spinnerModal);await wait(80);const target=((7-state.roll)%6)*60;const mod=((rotation%360)+360)%360;rotation+=1080+(target-mod);els.wheel.style.transform=`rotate(${rotation}deg)`;await wait(matchMedia("(prefers-reduced-motion: reduce)").matches?100:1650);els.rollCopy.textContent=`${tr("rolled")} ${state.roll} ${state.roll===1?tr("space"):tr("spaces")}!`;await wait(650);closeModal(els.spinnerModal);state.turns++;await animateMove(state.roll);showQuestion()
}
function showQuestion(){
  if(state.questionIndex>=questions.length){finishIfReady();return}const q=questions[state.questionIndex],data=q[state.lang];$("#question-stage").textContent=tr(`stage${q.stage+1}`);$("#question-count").textContent=`${tr("question")} ${state.questionIndex+1} ${tr("of")} ${questions.length}`;$("#question-text").textContent=data[0];els.answers.innerHTML="";els.feedback.className="feedback hidden";els.continue.classList.add("hidden");shuffledAnswers(data[1]).forEach(({text,originalIndex},displayIndex)=>{const b=document.createElement("button");b.className="answer";b.dataset.answerIndex=originalIndex;b.innerHTML=`<span class="answer-letter">${String.fromCharCode(65+displayIndex)}</span><span>${text}</span>`;b.onclick=()=>answerQuestion(originalIndex);els.answers.append(b)});openModal(els.questionModal)
}
function answerQuestion(choice){
  const q=questions[state.questionIndex],data=q[state.lang],correct=choice===data[2];$$('.answer').forEach(b=>{const answerIndex=Number(b.dataset.answerIndex);b.disabled=true;if(answerIndex===data[2])b.classList.add("correct");if(answerIndex===choice&&!correct)b.classList.add("wrong")});els.feedback.classList.remove("hidden");els.feedback.classList.toggle("wrong",!correct);$("#feedback-icon").textContent=correct?"✓":"!";$("#feedback-title").textContent=tr(correct?"correctTitle":"wrongTitle");$("#feedback-copy").textContent=`${tr(correct?"correctLead":"wrongLead")} ${data[3]}`;els.continue.classList.remove("hidden");state.questionIndex++;if(correct){state.correct++;state.grass++;playTone("good");reactCow("celebrate");growGrass()}else{playTone("bad");reactCow("sad")}els.continue.dataset.correct=String(correct);updateBoard()
}
async function continueJourney(){
  const wasCorrect=els.continue.dataset.correct==="true";closeModal(els.questionModal);if(!wasCorrect)await animateMove(-1);if(state.position>=24){finishGame()}else{state.busy=false;els.spin.disabled=false;showToast(wasCorrect?`♧  +1 ${tr("grass")}`:tr("wrongLead"))}
}
function finishIfReady(){if(state.position>=24)finishGame();else{state.busy=false;els.spin.disabled=false}}
function finishGame(){state.position=24;updateBoard();reactCow("arrived");$("#finish-correct").textContent=state.correct;$("#finish-grass").textContent=state.grass;$("#finish-turns").textContent=state.turns;setTimeout(()=>openModal(els.finishModal),650);launchConfetti();playTone("good")}
function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),1900)}
function reset(){Object.assign(state,{position:1,turns:0,grass:0,correct:0,questionIndex:0,busy:false,facing:"right",roll:1});rotation=0;els.wheel.style.transform="rotate(0deg)";$$('.modal').forEach(m=>m.classList.add("hidden"));els.backdrop.classList.add("hidden");els.spin.disabled=false;buildBoard()}
function applyLanguage(lang){state.lang=lang;document.documentElement.lang=lang;document.title=tr("title");$$('[data-i18n]').forEach(el=>{const value=tr(el.dataset.i18n);if(value)el.textContent=value});$$('.lang').forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));$("#sound-button").ariaLabel=tr(state.muted?"unmute":"mute");buildBoard()}
function launchConfetti(){const canvas=$("#confetti"),ctx=canvas.getContext("2d");canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const colors=["#a5bd67","#d8ad55","#fff4c9","#a9583b","#527749"],bits=Array.from({length:150},()=>({x:Math.random()*innerWidth,y:-Math.random()*innerHeight*.6,w:5+Math.random()*7,h:8+Math.random()*10,v:2+Math.random()*4,r:Math.random()*6,c:colors[Math.floor(Math.random()*colors.length)]}));let frames=0;(function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);bits.forEach(p=>{p.y+=p.v;p.r+=.08;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=p.c;ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.restore()});if(frames++<320)requestAnimationFrame(draw);else ctx.clearRect(0,0,innerWidth,innerHeight)})()}

els.spin.addEventListener("click",takeTurn);els.continue.addEventListener("click",continueJourney);$("#rules-button").addEventListener("click",()=>openModal(els.rulesModal));$("#rules-close").addEventListener("click",()=>closeModal(els.rulesModal));$("#close-game-button").addEventListener("click",()=>closeModal(els.finishModal));$$('.lang').forEach(b=>b.addEventListener("click",()=>applyLanguage(b.dataset.lang)));$("#sound-button").addEventListener("click",()=>{state.muted=!state.muted;$("#sound-button").textContent=state.muted?"×":"♪";$("#sound-button").title=tr(state.muted?"unmute":"mute")});
$("#replay-button").addEventListener("click",reset);$("#finish-replay-button").addEventListener("click",reset);
let resizeTimer;addEventListener("resize",()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(buildBoard,120)});applyLanguage("en");
