document.body.insertAdjacentHTML('afterbegin',`<div class="story-modal" id="story-modal" role="dialog" aria-modal="true" aria-labelledby="story-title"><div class="story-panel"><p class="kicker">DOLLY'S DAILY CARE</p><h1 id="story-title">Meet Dolly</h1><div class="official-copy"><p><strong>Intro: Dolly is a beautiful Jersey cow who carries the A2/A2 gene and produces rich, A2/A2 milk.</strong></p><p><strong>Help us take care of Dolly so she can stay healthy, happy, and produce nutritious raw milk.</strong></p><p><strong>Dolly needs nutritious food, water, companionship, health care, and shelter. And of course, don’t forget to milk her!&nbsp;</strong></p><p><strong>Let’s get started.&nbsp;</strong></p></div><button id="start-day" class="action" type="button">Start Dolly's day <span>→</span></button></div></div>`);
const steps=[
 {id:'food',title:'What should she eat?',copy:'It’s 10am! Time to feed Dolly! What should she eat? ',tip:'(Stomach rumbles)',gesture:'choose'},
 {id:'clean',title:'Clean her teats',copy:"It’s 4:30 am. Time to milk Dolly! Don’t forget to clean her teats with iodine. ",tip:'First cleaning',tool:'cloth',label:'Clean cloth',icon:'▧',art:'assets/tools/clean-cloth.png',gesture:'rub'},
 {id:'iodine',title:'Clean with iodine',copy:"It’s 4:30 am. Time to milk Dolly! Don’t forget to clean her teats with iodine. ",tip:'Iodine cleaning',tool:'cloth iodine-cloth',label:'Iodine cloth',icon:'▧',art:'assets/tools/iodine-cloth.png',gesture:'rub'},
 {id:'milk',title:'Milk Dolly',copy:'Milk Dolly',tip:'Slide down repeatedly, just like hand milking.',tool:'hand',label:'Milking hand',icon:'☝',gesture:'swipe'}
];
const goodFoods=['Pasture','Fodder','Organic alfalfa hay','Redmond conditioner','Sprouted barley (for treats!)','Redmond Real Salt','Molasses'];
const badFoods=['Corn','Soybeans','Spent grain from liquor and ethanol production','Candy bars','Potatoes','Bakery remnants'];
const allFoods=[...goodFoods,...badFoods];
let current=0,progress=0,dragging=false,dragOffset={x:0,y:0},audioContext,lastPoint=null,strokeStartY=0,milkPulls=0,foodSelected=new Set(),wrongFood=null;
const $=id=>document.getElementById(id);

function render(){
 const step=steps[current];progress=0;if(step.id==='milk')milkPulls=0;
 $('task-title').textContent=step.title;$('task-copy').textContent=step.copy;$('tip').textContent=step.tip;$('step-count').textContent=`${current+1} / ${steps.length}`;
 $('continue-btn').hidden=true;$('instruction').hidden=false;$('pasture').classList.toggle('feeding',step.id==='food');if(step.id==='food'){renderFood();return}window.dispatchEvent(new CustomEvent('dolly3d-action',{detail:'idle'}));$('instruction').innerHTML=step.gesture==='swipe'?'<span>↓</span> Pull downward and release 10 times.':`<span>↗</span> Move the ${step.label.toLowerCase()} back and forth over Dolly’s udder for about 5 seconds.`;
 $('pasture').classList.toggle('direct-milking',step.id==='milk');$('udder-target').className=`udder-target target-${step.id}`;$('udder-target').style.setProperty('--care-progress','0deg');
 if(step.id==='milk'){$('udder-target').innerHTML='<button class="udder-hotspot" aria-label="Milk Dolly by pulling downward on her udder"></button><div class="milk-stream" aria-hidden="true"></div><div class="bucket" aria-hidden="true"><div class="milk-level"></div><b></b></div>';$('tool-bay').innerHTML='<div class="gesture-demo"><i>☝</i><div><b>Milk Dolly directly</b><small>Press her udder and pull downward 10 times.</small></div></div>'}else{$('udder-target').innerHTML=`<span>${step.title}</span>`;$('tool-bay').innerHTML=step.art?`<button class="care-tool tool-image tool-${step.tool}" id="care-tool" type="button" aria-label="Drag ${step.label}"><img src="${step.art}" alt="" draggable="false"></button><small class="tool-hint">${step.label} · drag me</small><div class="cleaning-progress"><i id="cleaning-fill"></i></div>`:`<button class="care-tool tool-${step.tool}" id="care-tool" type="button" aria-label="Drag ${step.label}"><b>${step.icon}</b><span>${step.label}</span><small>DRAG ME</small></button><div class="cleaning-progress"><i id="cleaning-fill"></i></div>`}
 $('progress-steps').innerHTML=steps.map((item,i)=>`<div class="progress-step ${i<current?'done':''} ${i===current?'active':''}"><i>${i<current?'✓':i+1}</i><span>${item.title}</span></div>`).join('');
 $('status').textContent=`${step.title}: waiting for you.`;setDolly(step.id==='milk'?'tail':'idle');step.id==='milk'?bindMilking():bindGesture();
}
function foodArt(food){const index=allFoods.indexOf(food);return `<i class="food-art" style="--c:${index%4};--r:${Math.floor(index/4)}"></i>`}
function renderFood(message='Choose foods and place them in Dolly’s feeder.'){const firstLoad=!$('pasture').classList.contains('feeding');$('pasture').classList.remove('direct-milking');$('pasture').classList.add('feeding');$('udder-target').className='udder-target food-trough';setDolly(wrongFood?'bad':'lowered');if(firstLoad){foodSelected.clear();wrongFood=null}$('udder-target').innerHTML=`<div class="trough-food">${[...foodSelected].map(food=>`<span title="${food}">${foodArt(food)}</span>`).join('')}${wrongFood?`<button class="trough-wrong" id="remove-wrong" type="button" aria-label="Remove ${wrongFood}">${foodArt(wrongFood)}<b>×</b></button>`:''}</div>`;const choices=[...allFoods].sort((a,b)=>allFoods.indexOf(a)-allFoods.indexOf(b));$('tool-bay').innerHTML=`<div class="food-grid">${choices.map(food=>`<button class="food-choice ${foodSelected.has(food)?'selected':''} ${wrongFood===food?'wrong':''}" data-food="${food}" ${wrongFood||foodSelected.has(food)?'disabled':''}>${foodArt(food)}<span>${food}</span></button>`).join('')}</div>`;$('instruction').innerHTML=`<span>${wrongFood?'!':'♪'}</span> ${message}`;$('status').textContent=wrongFood?'Remove the wrong food from Dolly’s feeder.':'Dolly’s stomach is rumbling.';if(wrongFood){$('speech').textContent='Moo… no thanks!';window.dispatchEvent(new CustomEvent('dolly3d-action',{detail:'bad'}));$('remove-wrong').addEventListener('click',()=>{wrongFood=null;$('speech').textContent='Moooo!';renderFood('Good catch. Keep building Dolly’s ration.')});return}$('speech').textContent='Mmmmooo!';document.querySelectorAll('.food-choice').forEach(button=>button.addEventListener('click',()=>{const food=button.dataset.food;if(badFoods.includes(food)){wrongFood=food;tone(180,.045,.2);renderFood('That food does not belong. Tap it in the feeder to remove it.');return}foodSelected.add(food);tone(520,.025,.08);renderFood(`${foodSelected.size} of ${goodFoods.length} correct foods are in the feeder.`);window.dispatchEvent(new CustomEvent('dolly3d-action',{detail:'eat'}));if(foodSelected.size===goodFoods.length)completeFood()}))}
function completeFood(){$('continue-btn').hidden=false;$('continue-btn').innerHTML='Feed Dolly <span>→</span>';$('instruction').innerHTML='<span>✓</span> All of Dolly’s nutritious foods are ready.';$('status').textContent='The feeding choices are correct.';$('score').textContent='25%';$('meter-fill').style.width='25%';setDolly('happy');successSound()}
function bindMilking(){const hotspot=document.querySelector('.udder-hotspot'),stream=document.querySelector('.milk-stream');let startY=0,lastY=0,validPull=false;let stopStream;$('udder-target').style.setProperty('--milk-level','0%');hotspot.addEventListener('pointerdown',e=>{e.preventDefault();dragging=true;validPull=false;startY=lastY=e.clientY;hotspot.setPointerCapture(e.pointerId);hotspot.classList.add('pulling');const box=$('udder-target').getBoundingClientRect(),cowScale=parseFloat(getComputedStyle($('pasture')).getPropertyValue('--cow-scale'))||1;$('udder-target').style.setProperty('--stream-x',`${Math.max(-5,Math.min(105,(e.clientX-box.left)/cowScale))}px`);$('status').textContent=`Pull downward · ${milkPulls} of 10 pulls`});hotspot.addEventListener('pointermove',e=>{if(!dragging)return;e.preventDefault();const delta=e.clientY-lastY,total=e.clientY-startY;if(delta>0&&total>12){validPull=true;hotspot.style.transform=`translateY(${Math.min(total,18)}px)`;stream.classList.add('flowing');clearTimeout(stopStream);stopStream=setTimeout(()=>stream.classList.remove('flowing'),100)}lastY=e.clientY});const release=()=>{if(!dragging)return;dragging=false;hotspot.classList.remove('pulling');hotspot.removeAttribute('style');stream.classList.remove('flowing');if(validPull){milkPulls=Math.min(10,milkPulls+1);progress=milkPulls*10;$('udder-target').style.setProperty('--milk-level',`${progress}%`);$('status').textContent=milkPulls<10?`${milkPulls} of 10 pulls · keep milking Dolly.`:'10 of 10 pulls · the bucket is full!';tone(430+milkPulls*8,.025,.07);if(milkPulls===10)completeMilking()}else $('status').textContent='Pull farther downward to count this stroke.'};hotspot.addEventListener('pointerup',release);hotspot.addEventListener('pointercancel',release)}
function completeMilking(){if($('udder-target').classList.contains('complete'))return;dragging=false;$('udder-target').classList.add('complete');document.querySelector('.udder-hotspot').disabled=true;document.querySelector('.milk-stream').classList.remove('flowing');$('instruction').hidden=true;$('continue-btn').hidden=false;$('continue-btn').innerHTML='Finish morning care <span>→</span>';$('status').textContent='Milk Dolly complete. Dolly is comfortable.';$('score').textContent='100%';$('meter-fill').style.width='100%';setDolly('happy');$('speech').textContent='Moooo! All done!';$('pasture').classList.add('celebrate');successSound()}
function bindGesture(){const tool=$('care-tool');tool.addEventListener('pointerdown',e=>{dragging=true;tool.setPointerCapture(e.pointerId);const r=tool.getBoundingClientRect();dragOffset={x:e.clientX-r.left,y:e.clientY-r.top};lastPoint={x:e.clientX,y:e.clientY,time:performance.now()};tool.classList.add('dragging');moveTool(e);tone(340,.05)});tool.addEventListener('pointermove',e=>dragging&&moveTool(e));tool.addEventListener('pointerup',finishDrag);tool.addEventListener('pointercancel',resetTool)}
function moveTool(e){const tool=$('care-tool');tool.style.position='fixed';tool.style.zIndex='20';tool.style.left=`${e.clientX-dragOffset.x}px`;tool.style.top=`${e.clientY-dragOffset.y}px`;const hit=overlaps(tool,$('udder-target')),now=performance.now();$('udder-target').classList.toggle('engaged',hit);if(hit&&lastPoint){const distance=Math.hypot(e.clientX-lastPoint.x,e.clientY-lastPoint.y),elapsed=Math.min(80,now-lastPoint.time);if(distance>1.5)progress=Math.min(100,progress+elapsed/50);$('udder-target').style.setProperty('--care-progress',`${progress*3.6}deg`);const fill=$('cleaning-fill');if(fill)fill.style.width=`${progress}%`;$('status').textContent=`Cleaning with iodine · ${Math.round(progress)}%`;if(progress>=100)completeStep()}lastPoint={x:e.clientX,y:e.clientY,time:now}}
function finishDrag(){dragging=false;if(progress>=100)return;resetTool();$('status').textContent=progress?'Good start — keep the tool on the target.':'Try placing the tool on the glowing ring.'}
function resetTool(){dragging=false;const tool=$('care-tool');if(!tool)return;tool.classList.remove('dragging');tool.removeAttribute('style');$('udder-target').classList.remove('engaged')}
function completeStep(){dragging=false;const step=steps[current],tool=$('care-tool');tool.classList.add('complete');$('udder-target').classList.add('complete');$('instruction').hidden=true;$('continue-btn').hidden=false;$('continue-btn').innerHTML=current===steps.length-1?'Finish morning care <span>→</span>':'Next step <span>→</span>';$('status').textContent=`${step.title} complete. Dolly is comfortable.`;$('score').textContent=`${Math.round((current+1)/steps.length*100)}%`;$('meter-fill').style.width=`${(current+1)/steps.length*100}%`;setDolly('happy');$('speech').textContent=current===2?'Moooo! All done!':'Mooo, thank you!';$('pasture').classList.add('celebrate');successSound();setTimeout(()=>$('pasture').classList.remove('celebrate'),900)}
function setDolly(pose){$('dolly').className=`dolly-sprite pose-${pose}`;$('dolly-wrap').className=`dolly-wrap mood-${pose}`;if(pose==='happy')window.dispatchEvent(new CustomEvent('dolly3d-action',{detail:'happy'}))}
function overlaps(a,b){const x=a.getBoundingClientRect(),y=b.getBoundingClientRect();return x.left<y.right&&x.right>y.left&&x.top<y.bottom&&x.bottom>y.top}
function tone(f,v=.035,d=.08){try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=f;g.gain.value=v;o.connect(g).connect(audioContext.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+d);o.stop(audioContext.currentTime+d)}catch(_){}}
// Dolly's moo: a real recording (assets/audio/moo.m4a, CC BY-SA — see assets/audio/CREDITS.txt).
const mooClip=new Audio('assets/audio/moo.m4a');mooClip.preload='auto';mooClip.volume=.85;
function moo(){try{mooClip.currentTime=0;mooClip.play().catch(()=>{})}catch(_){}}
function successSound(){[440,554,659].forEach((n,i)=>setTimeout(()=>tone(n,.04,.18),i*100))}
$('continue-btn').addEventListener('click',()=>{if(current<steps.length-1){current++;render();return}$('task-title').textContent='Morning care complete!';$('task-copy').textContent='Dolly is clean, comfortable, and ready for breakfast.';$('tool-bay').innerHTML='<div class="milk-result"><span>🥛</span><div><b>Fresh A2/A2 milk</b><small>Clean · cooled · cared for</small></div></div>';$('udder-target').classList.add('hidden');$('instruction').hidden=true;$('continue-btn').hidden=true;$('progress-steps').innerHTML=steps.map(item=>`<div class="progress-step done"><i>✓</i><span>${item.title}</span></div>`).join('');$('status').textContent='Morning milking complete. Breakfast is next!';$('speech').textContent='Breakfast time!';setDolly('happy');window.dispatchEvent(new CustomEvent('dolly3d-action',{detail:'celebrate'}));setTimeout(moo,600)});
$('start-day').addEventListener('click',()=>{$('story-modal').classList.add('dismissed');window.dispatchEvent(new CustomEvent('dolly3d-action',{detail:'enter'}));tone(760,.05,.18);setTimeout(()=>tone(540,.04,.28),130)});
$('restart')?.addEventListener('click',()=>{current=0;foodSelected.clear();wrongFood=null;$('pasture').classList.remove('feeding');$('score').textContent='0%';$('meter-fill').style.width='0';$('speech').textContent='Mooooorning!';render()});render();
if(new URLSearchParams(location.search).has('preview3d'))$('story-modal').classList.add('dismissed');
