(function () {
  const contributionFrequencies = {
    monthly: { periods: 12 },
    yearly: { periods: 1 },
  };

  const compoundFrequencies = {
    annually: { periods: 1 },
    semiannually: { periods: 2 },
    quarterly: { periods: 4 },
    monthly: { periods: 12 },
    semimonthly: { periods: 24 },
    biweekly: { periods: 26 },
    weekly: { periods: 52 },
    daily: { periods: 365 },
    continuous: { periods: Infinity },
  };

  const modeConfig = {
    endBalance: { hiddenFields: ["targetAmountGroup"] },
    contribution: { hiddenFields: ["contributionAmountGroup"] },
    rate: { hiddenFields: ["annualRateGroup"] },
    startingAmount: { hiddenFields: ["initialAmountGroup"] },
    length: { hiddenFields: ["yearsGroup"] },
  };

  const copy = {
    fields: {
      targetAmount: "Target amount",
      initialAmount: "Starting amount",
      contributionAmount: "Additional contribution",
    },
    modes: {
      endBalance: {
        label: "Ending balance",
        helper:
          "Projects how much the investment could be worth at the end of the horizon using your contributions and selected rate.",
        resultsTitle: "Portfolio projection",
      },
      contribution: {
        label: "Additional contribution",
        helper:
          "Calculates what additional contribution per period would be needed to reach the target within the selected time frame.",
        resultsTitle: "Suggested additional contribution",
      },
      rate: {
        label: "Required rate",
        helper:
          "Estimates the nominal annual rate you would need to reach the target with the current contribution plan.",
        resultsTitle: "Rate needed to hit the target",
      },
      startingAmount: {
        label: "Starting amount",
        helper:
          "Solves for how much you should invest upfront to reach the target without changing contributions or length.",
        resultsTitle: "Recommended starting amount",
      },
      length: {
        label: "Time to goal",
        helper:
          "Calculates how long it would take to reach the target while keeping the starting amount, rate, and contributions unchanged.",
        resultsTitle: "Estimated time to reach the goal",
      },
    },
    metrics: {
      effectiveReturn: "Effective return",
      targetGoal: "Target goal",
    },
    chart: {
      legend: {
        principal: "Starting Amount",
        contributions: "Contributions",
        interest: "Interest",
      },
    },
    words: {
      and: "and",
    },
    units: {
      year: { one: "year", other: "years" },
      month: { one: "month", other: "months" },
    },
    periodTokens: {
      year: "Year",
      month: "Month",
    },
    frequencyDescriptors: {
      monthly: "monthly",
      yearly: "annual",
    },
    validation: {
      nonNegative: (label) => `"${label}" must be a number greater than or equal to 0.`,
      years: '"Time horizon" must be a number greater than or equal to 0.',
      annualRate: '"Nominal annual return" must be between -99 and 1000.',
    },
    errors: {
      invalidRateFrequency: "The selected rate and compounding frequency combination is not valid.",
      invalidEffectiveRate: "The resulting effective annual rate cannot be converted to the selected period.",
      contributionSearch: "No reasonable contribution was found within the search range.",
      startingAmountSearch: "No reasonable starting amount was found within the search range.",
      rateOutOfRange: "The goal requires a rate outside the range covered by this first version.",
      lengthOutOfRange:
        "The goal is not reached within the 120-year maximum configured in this version.",
      generic: "The scenario could not be calculated.",
    },
    templates: {
      investedHint: ({ contributions, frequency }) =>
        `Includes ${contributions} in ${frequency} contributions plus the starting amount.`,
      interestPositive: "Estimated net gain generated by compound growth.",
      interestNegative: "This scenario ends below the capital invested.",
      effectiveReturnHint:
        "Annual conversion after applying the selected compounding frequency.",
      targetGoalHint: "Final value used to solve the calculation.",
      contributionSummary: ({ target, durationLabel, solvedValue }) =>
        `To reach ${target} in ${durationLabel}, this model estimates a contribution of about ${solvedValue} per period.`,
      rateSummary: ({ target, durationLabel, solvedValue }) =>
        `To reach ${target} in ${durationLabel}, the required nominal annual return lands around ${solvedValue}.`,
      startingAmountSummary: ({ target, durationLabel, solvedValue }) =>
        `With the current contribution plan and a horizon of ${durationLabel}, you would need to start with about ${solvedValue} to reach ${target}.`,
      lengthSummary: ({ target, durationLabel }) =>
        `Keeping this contribution pace and selected rate, the ${target} goal would be reached in about ${durationLabel}.`,
      endBalanceSummary: ({ initialAmount, contributionAmount, contributionFrequency, endingBalance, durationLabel }) =>
        `Starting with ${initialAmount} and ${contributionAmount} ${contributionFrequency} contributions, the balance could close at ${endingBalance} after ${durationLabel}.`,
      contributionMetricHint: "Estimated for each additional contribution period.",
      rateMetricHint: ({ durationLabel }) =>
        `Nominal annual return for a ${durationLabel} horizon.`,
      startingAmountMetricHint: "Estimated upfront amount needed to support the goal.",
      lengthMetricHint: ({ target }) =>
        `Target ${target} reached under this scenario.`,
      endBalanceMetricHint: ({ durationLabel }) =>
        `Path calculated for ${durationLabel}.`,
      compositionPositive: ({ endingBalance }) =>
        `Ending balance: ${endingBalance}`,
      compositionNegative: ({ totalInvested, endingBalance }) =>
        `Amount invested: ${totalInvested} · ending balance: ${endingBalance}`,
      tableSummary: ({ count, durationLabel }) =>
        `${count} checkpoints shown · projected horizon: ${durationLabel}`,
    },
  };

  let currencyFormatter;
  let currencyFormatterPrecise;
  let currencyCompactFormatter;
  let numberFormatter;
  let percentFormatter;

  const form = document.getElementById("calculator-form");
  const modeSelect = document.getElementById("modeSelect");
  const modeHelper = document.getElementById("modeHelper");
  const errorBox = document.getElementById("errorBox");
  const modePill = document.getElementById("modePill");
  const resultsTitle = document.getElementById("resultsTitle");
  const resultsSummary = document.getElementById("resultsSummary");
  const primaryMetricLabel = document.getElementById("primaryMetricLabel");
  const primaryMetricValue = document.getElementById("primaryMetricValue");
  const primaryMetricHint = document.getElementById("primaryMetricHint");
  const investedValue = document.getElementById("investedValue");
  const investedHint = document.getElementById("investedHint");
  const interestValue = document.getElementById("interestValue");
  const interestHint = document.getElementById("interestHint");
  const secondaryMetricLabel = document.getElementById("secondaryMetricLabel");
  const secondaryMetricValue = document.getElementById("secondaryMetricValue");
  const secondaryMetricHint = document.getElementById("secondaryMetricHint");
  const compositionMeta = document.getElementById("compositionMeta");
  const principalSegment = document.getElementById("principalSegment");
  const contributionSegment = document.getElementById("contributionSegment");
  const interestSegment = document.getElementById("interestSegment");
  const lossSegment = document.getElementById("lossSegment");
  const principalLegend = document.getElementById("principalLegend");
  const contributionLegend = document.getElementById("contributionLegend");
  const interestLegend = document.getElementById("interestLegend");
  const lossLegend = document.getElementById("lossLegend");
  const lossLegendItem = document.getElementById("lossLegendItem");
  const growthChart = document.getElementById("growthChart");
  const chartLegend = document.getElementById("chartLegend");
  const chartEmpty = document.getElementById("chartEmpty");
  const scheduleBody = document.getElementById("scheduleBody");
  const tableSummary = document.getElementById("tableSummary");

  const fieldGroups = {
    targetAmountGroup: document.getElementById("targetAmountGroup"),
    initialAmountGroup: document.getElementById("initialAmountGroup"),
    contributionAmountGroup: document.getElementById("contributionAmountGroup"),
    yearsGroup: document.getElementById("yearsGroup"),
    annualRateGroup: document.getElementById("annualRateGroup"),
  };

  syncFormatters();

  let currentMode = "endBalance";

  function syncFormatters() {
    const locale = "en-US";
    currencyFormatter = new Intl.NumberFormat(locale, {
      style: "currency",
      currency: "USD",
      maximumFractionDigits: 0,
    });
    currencyFormatterPrecise = new Intl.NumberFormat(locale, {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
    currencyCompactFormatter = new Intl.NumberFormat(locale, {
      style: "currency",
      currency: "USD",
      notation: "compact",
      maximumFractionDigits: 1,
    });
    numberFormatter = new Intl.NumberFormat(locale, {
      maximumFractionDigits: 1,
      minimumFractionDigits: 0,
    });
    percentFormatter = new Intl.NumberFormat(locale, {
      maximumFractionDigits: 2,
      minimumFractionDigits: 2,
    });
  }

  function pluralize(unit, count) {
    const forms = copy.units[unit];
    return Math.abs(count) === 1 ? forms.one : forms.other;
  }

  function formatCurrency(value, precise = false) {
    const formatter = precise ? currencyFormatterPrecise : currencyFormatter;
    return formatter.format(Number.isFinite(value) ? value : 0);
  }

  function formatPercent(value) {
    return percentFormatter.format(value) + "%";
  }

  function formatCurrencyCompact(value) {
    return currencyCompactFormatter.format(Number.isFinite(value) ? value : 0);
  }

  function clampNonNegative(value, label) {
    if (!Number.isFinite(value) || value < 0) {
      throw new Error(copy.validation.nonNegative(label));
    }
    return value;
  }

  function readNumber(id) {
    const rawValue = document.getElementById(id).value;
    return rawValue === "" ? Number.NaN : Number(rawValue);
  }

  function getEffectiveAnnualRate(nominalRatePercent, compoundKey) {
    const nominalRate = nominalRatePercent / 100;
    if (compoundKey === "continuous") {
      return Math.exp(nominalRate) - 1;
    }

    const frequency = compoundFrequencies[compoundKey];
    const base = 1 + nominalRate / frequency.periods;
    if (base <= 0) {
      throw new Error(copy.errors.invalidRateFrequency);
    }

    return Math.pow(base, frequency.periods) - 1;
  }

  function getPeriodRate(annualRatePercent, compoundKey, periodsPerYear) {
    const effectiveAnnualRate = getEffectiveAnnualRate(annualRatePercent, compoundKey);
    const periodBase = 1 + effectiveAnnualRate;
    if (periodBase < 0) {
      throw new Error(copy.errors.invalidEffectiveRate);
    }
    return Math.pow(periodBase, 1 / periodsPerYear) - 1;
  }

  function simulateProjection({
    initialAmount,
    contributionAmount,
    years,
    annualRate,
    contributionFrequency,
    contributionTiming,
    compoundFrequency,
  }) {
    const frequency = contributionFrequencies[contributionFrequency];
    const periodsPerYear = frequency.periods;
    const totalPeriods = Math.max(0, Math.round(years * periodsPerYear));
    const periodRate = getPeriodRate(annualRate, compoundFrequency, periodsPerYear);
    const effectiveAnnualRate = getEffectiveAnnualRate(annualRate, compoundFrequency);

    let balance = initialAmount;
    let periodicContributions = 0;
    const yearRows = [];
    const points = [{ time: 0, value: balance }];
    let yearContribution = 0;
    let yearInterest = 0;

    for (let period = 1; period <= totalPeriods; period += 1) {
      const deposit = contributionAmount;
      let interestForPeriod = 0;

      if (contributionTiming === "beginning" && deposit > 0) {
        balance += deposit;
        periodicContributions += deposit;
        yearContribution += deposit;
      }

      interestForPeriod = balance * periodRate;
      balance += interestForPeriod;
      yearInterest += interestForPeriod;

      if (contributionTiming === "end" && deposit > 0) {
        balance += deposit;
        periodicContributions += deposit;
        yearContribution += deposit;
      }

      const snapshotDue = period % periodsPerYear === 0 || period === totalPeriods;
      if (snapshotDue) {
        const yearsElapsed = period / periodsPerYear;
        yearRows.push({
          label: buildPeriodLabel(period, periodsPerYear),
          contribution: yearContribution,
          interest: yearInterest,
          endingBalance: balance,
          yearsElapsed,
        });
        points.push({ time: yearsElapsed, value: balance });
        yearContribution = 0;
        yearInterest = 0;
      }
    }

    return {
      endingBalance: balance,
      totalInvested: initialAmount + periodicContributions,
      periodicContributions,
      totalInterest: balance - (initialAmount + periodicContributions),
      effectiveAnnualRate,
      periodsPerYear,
      totalPeriods,
      yearRows,
      points,
    };
  }

  function buildPeriodLabel(period, periodsPerYear) {
    if (periodsPerYear === 12) {
      if (period % 12 === 0) {
        return `${copy.periodTokens.year} ${period / 12}`;
      }
      const wholeYears = Math.floor(period / 12);
      const remainingMonths = period % 12;
      if (wholeYears === 0) {
        return `${copy.periodTokens.month} ${remainingMonths}`;
      }
      return `${copy.periodTokens.year} ${wholeYears} + ${remainingMonths}m`;
    }

    if (periodsPerYear === 1) {
      return `${copy.periodTokens.year} ${period}`;
    }

    const yearsElapsed = period / periodsPerYear;
    return `${numberFormatter.format(yearsElapsed)} ${pluralize("year", yearsElapsed)}`;
  }

  function collectInputs() {
    const rawTargetAmount = readNumber("targetAmount");
    const rawInitialAmount = readNumber("initialAmount");
    const rawContributionAmount = readNumber("contributionAmount");
    const rawYears = readNumber("years");
    const rawAnnualRate = readNumber("annualRate");
    const contributionFrequency = document.getElementById("contributionFrequency").value;
    const contributionTiming = document.getElementById("contributionTiming").value;
    const compoundFrequency = document.getElementById("compoundFrequency").value;

    const targetAmount =
      currentMode === "endBalance" && !Number.isFinite(rawTargetAmount)
        ? 0
        : clampNonNegative(rawTargetAmount, copy.fields.targetAmount);

    const initialAmount =
      currentMode === "startingAmount" && !Number.isFinite(rawInitialAmount)
        ? 0
        : clampNonNegative(rawInitialAmount, copy.fields.initialAmount);

    const contributionAmount =
      currentMode === "contribution" && !Number.isFinite(rawContributionAmount)
        ? 0
        : clampNonNegative(rawContributionAmount, copy.fields.contributionAmount);

    let years = rawYears;
    if (currentMode === "length" && !Number.isFinite(rawYears)) {
      years = 0;
    } else if (!Number.isFinite(rawYears) || rawYears < 0) {
      throw new Error(copy.validation.years);
    }

    let annualRate = rawAnnualRate;
    if (currentMode === "rate" && !Number.isFinite(rawAnnualRate)) {
      annualRate = 7;
    } else if (!Number.isFinite(rawAnnualRate) || rawAnnualRate < -99 || rawAnnualRate > 1000) {
      throw new Error(copy.validation.annualRate);
    }

    return {
      targetAmount,
      initialAmount,
      contributionAmount,
      years,
      annualRate,
      contributionFrequency,
      contributionTiming,
      compoundFrequency,
    };
  }

  function solveScenario(inputs) {
    switch (currentMode) {
      case "endBalance":
        return {
          simulation: simulateProjection(inputs),
          solvedValue: null,
          targetAmount: null,
        };

      case "contribution":
        return solveContribution(inputs);

      case "rate":
        return solveRate(inputs);

      case "startingAmount":
        return solveStartingAmount(inputs);

      case "length":
        return solveLength(inputs);

      default:
        return {
          simulation: simulateProjection(inputs),
          solvedValue: null,
          targetAmount: null,
        };
    }
  }

  function solveContribution(inputs) {
    const periodsPerYear = contributionFrequencies[inputs.contributionFrequency].periods;
    const baseline = simulateProjection({ ...inputs, contributionAmount: 0 });
    if (baseline.endingBalance >= inputs.targetAmount) {
      return {
        simulation: baseline,
        solvedValue: 0,
        targetAmount: inputs.targetAmount,
      };
    }

    let low = 0;
    let high = Math.max(100, inputs.targetAmount / Math.max(1, inputs.years * periodsPerYear));
    let projection = simulateProjection({ ...inputs, contributionAmount: high });

    while (projection.endingBalance < inputs.targetAmount && high < 10000000) {
      high *= 2;
      projection = simulateProjection({ ...inputs, contributionAmount: high });
    }

    if (projection.endingBalance < inputs.targetAmount) {
      throw new Error(copy.errors.contributionSearch);
    }

    for (let step = 0; step < 80; step += 1) {
      const midpoint = (low + high) / 2;
      const attempt = simulateProjection({ ...inputs, contributionAmount: midpoint });
      if (attempt.endingBalance >= inputs.targetAmount) {
        high = midpoint;
        projection = attempt;
      } else {
        low = midpoint;
      }
    }

    return {
      simulation: projection,
      solvedValue: high,
      targetAmount: inputs.targetAmount,
    };
  }

  function solveStartingAmount(inputs) {
    const periodsPerYear = contributionFrequencies[inputs.contributionFrequency].periods;
    const baseline = simulateProjection({ ...inputs, initialAmount: 0 });
    if (baseline.endingBalance >= inputs.targetAmount) {
      return {
        simulation: baseline,
        solvedValue: 0,
        targetAmount: inputs.targetAmount,
      };
    }

    let low = 0;
    let high = Math.max(inputs.targetAmount, inputs.contributionAmount * inputs.years * periodsPerYear);
    let projection = simulateProjection({ ...inputs, initialAmount: high });

    while (projection.endingBalance < inputs.targetAmount && high < 1000000000) {
      high *= 2;
      projection = simulateProjection({ ...inputs, initialAmount: high });
    }

    if (projection.endingBalance < inputs.targetAmount) {
      throw new Error(copy.errors.startingAmountSearch);
    }

    for (let step = 0; step < 80; step += 1) {
      const midpoint = (low + high) / 2;
      const attempt = simulateProjection({ ...inputs, initialAmount: midpoint });
      if (attempt.endingBalance >= inputs.targetAmount) {
        high = midpoint;
        projection = attempt;
      } else {
        low = midpoint;
      }
    }

    return {
      simulation: projection,
      solvedValue: high,
      targetAmount: inputs.targetAmount,
    };
  }

  function solveRate(inputs) {
    const lowRate = -99;
    let lowProjection = simulateProjection({ ...inputs, annualRate: lowRate });
    if (lowProjection.endingBalance >= inputs.targetAmount) {
      return {
        simulation: lowProjection,
        solvedValue: lowRate,
        targetAmount: inputs.targetAmount,
      };
    }

    let low = lowRate;
    let high = Math.max(6, inputs.annualRate);
    let highProjection = simulateProjection({ ...inputs, annualRate: high });

    while (highProjection.endingBalance < inputs.targetAmount && high < 1000) {
      high = high < 24 ? high * 2 : high + 20;
      highProjection = simulateProjection({ ...inputs, annualRate: high });
    }

    if (highProjection.endingBalance < inputs.targetAmount) {
      throw new Error(copy.errors.rateOutOfRange);
    }

    let bestProjection = highProjection;
    for (let step = 0; step < 100; step += 1) {
      const midpoint = (low + high) / 2;
      const attempt = simulateProjection({ ...inputs, annualRate: midpoint });
      if (attempt.endingBalance >= inputs.targetAmount) {
        high = midpoint;
        bestProjection = attempt;
      } else {
        low = midpoint;
        lowProjection = attempt;
      }
    }

    return {
      simulation: bestProjection,
      solvedValue: high,
      targetAmount: inputs.targetAmount,
    };
  }

  function solveLength(inputs) {
    if (inputs.initialAmount >= inputs.targetAmount) {
      return {
        simulation: simulateProjection({ ...inputs, years: 0 }),
        solvedValue: 0,
        solvedPeriods: 0,
        targetAmount: inputs.targetAmount,
      };
    }

    const periodsPerYear = contributionFrequencies[inputs.contributionFrequency].periods;
    const periodRate = getPeriodRate(inputs.annualRate, inputs.compoundFrequency, periodsPerYear);
    const maxPeriods = periodsPerYear * 120;
    let balance = inputs.initialAmount;

    for (let period = 1; period <= maxPeriods; period += 1) {
      if (inputs.contributionTiming === "beginning" && inputs.contributionAmount > 0) {
        balance += inputs.contributionAmount;
      }

      balance += balance * periodRate;

      if (inputs.contributionTiming === "end" && inputs.contributionAmount > 0) {
        balance += inputs.contributionAmount;
      }

      if (balance >= inputs.targetAmount) {
        const years = period / periodsPerYear;
        return {
          simulation: simulateProjection({ ...inputs, years }),
          solvedValue: years,
          solvedPeriods: period,
          targetAmount: inputs.targetAmount,
        };
      }
    }

    throw new Error(copy.errors.lengthOutOfRange);
  }

  function formatDuration(totalPeriods, periodsPerYear) {
    if (totalPeriods === 0) {
      return `0 ${pluralize("year", 0)}`;
    }

    if (periodsPerYear === 12) {
      const years = Math.floor(totalPeriods / 12);
      const months = totalPeriods % 12;
      if (years === 0) {
        return `${months} ${pluralize("month", months)}`;
      }
      if (months === 0) {
        return `${years} ${pluralize("year", years)}`;
      }
      return `${years} ${pluralize("year", years)} ${copy.words.and} ${months} ${pluralize("month", months)}`;
    }

    if (periodsPerYear === 1) {
      return `${totalPeriods} ${pluralize("year", totalPeriods)}`;
    }

    const years = totalPeriods / periodsPerYear;
    return `${numberFormatter.format(years)} ${pluralize("year", years)}`;
  }

  function renderScenario(inputs, scenario) {
    hideError();

    const simulation = scenario.simulation;
    const endingBalance = simulation.endingBalance;
    const totalInvested = simulation.totalInvested;
    const totalInterest = simulation.totalInterest;
    const durationLabel = formatDuration(simulation.totalPeriods, simulation.periodsPerYear);
    const contributionLabel = copy.frequencyDescriptors[inputs.contributionFrequency];

    resultsTitle.textContent = buildResultsTitle();
    resultsSummary.textContent = buildSummaryText(inputs, scenario, durationLabel);
    modePill.textContent = copy.modes[currentMode].label;

    const primaryMetric = buildPrimaryMetric(inputs, scenario, durationLabel);
    primaryMetricLabel.textContent = primaryMetric.label;
    primaryMetricValue.textContent = primaryMetric.value;
    primaryMetricHint.textContent = primaryMetric.hint;

    investedValue.textContent = formatCurrency(totalInvested);
    investedHint.textContent = copy.templates.investedHint({
      contributions: formatCurrency(simulation.periodicContributions),
      frequency: contributionLabel,
    });

    interestValue.textContent = formatCurrency(totalInterest);
    interestHint.textContent =
      totalInterest >= 0
        ? copy.templates.interestPositive
        : copy.templates.interestNegative;

    const secondaryMetric = buildSecondaryMetric(scenario, simulation);
    secondaryMetricLabel.textContent = secondaryMetric.label;
    secondaryMetricValue.textContent = secondaryMetric.value;
    secondaryMetricHint.textContent = secondaryMetric.hint;

    renderComposition(simulation);
    renderChart(simulation);
    renderTable(simulation.yearRows, durationLabel, endingBalance);
  }

  function buildResultsTitle() {
    return copy.modes[currentMode].resultsTitle;
  }

  function buildSummaryText(inputs, scenario, durationLabel) {
    const target = scenario.targetAmount ? formatCurrency(scenario.targetAmount) : "";

    switch (currentMode) {
      case "contribution":
        return copy.templates.contributionSummary({
          target,
          durationLabel,
          solvedValue: formatCurrency(scenario.solvedValue, true),
        });

      case "rate":
        return copy.templates.rateSummary({
          target,
          durationLabel,
          solvedValue: formatPercent(scenario.solvedValue),
        });

      case "startingAmount":
        return copy.templates.startingAmountSummary({
          target,
          durationLabel,
          solvedValue: formatCurrency(scenario.solvedValue, true),
        });

      case "length":
        return copy.templates.lengthSummary({
          target,
          durationLabel: formatDuration(
            scenario.solvedPeriods,
            scenario.simulation.periodsPerYear
          ),
        });

      default:
        return copy.templates.endBalanceSummary({
          initialAmount: formatCurrency(inputs.initialAmount),
          contributionAmount: formatCurrency(inputs.contributionAmount),
          contributionFrequency: copy.frequencyDescriptors[inputs.contributionFrequency],
          endingBalance: formatCurrency(scenario.simulation.endingBalance),
          durationLabel,
        });
    }
  }

  function buildPrimaryMetric(inputs, scenario, durationLabel) {
    switch (currentMode) {
      case "contribution":
        return {
          label: copy.modes.contribution.label,
          value: formatCurrency(scenario.solvedValue),
          hint: copy.templates.contributionMetricHint,
        };

      case "rate":
        return {
          label: copy.modes.rate.label,
          value: formatPercent(scenario.solvedValue),
          hint: copy.templates.rateMetricHint({ durationLabel }),
        };

      case "startingAmount":
        return {
          label: copy.modes.startingAmount.label,
          value: formatCurrency(scenario.solvedValue),
          hint: copy.templates.startingAmountMetricHint,
        };

      case "length":
        return {
          label: copy.modes.length.label,
          value: formatDuration(scenario.solvedPeriods, scenario.simulation.periodsPerYear),
          hint: copy.templates.lengthMetricHint({
            target: formatCurrency(scenario.targetAmount),
          }),
        };

      default:
        return {
          label: copy.modes.endBalance.label,
          value: formatCurrency(scenario.simulation.endingBalance),
          hint: copy.templates.endBalanceMetricHint({ durationLabel }),
        };
    }
  }

  function buildSecondaryMetric(scenario, simulation) {
    if (currentMode === "endBalance") {
      return {
        label: copy.metrics.effectiveReturn,
        value: formatPercent(simulation.effectiveAnnualRate * 100),
        hint: copy.templates.effectiveReturnHint,
      };
    }

    return {
      label: copy.metrics.targetGoal,
      value: formatCurrency(scenario.targetAmount || simulation.endingBalance),
      hint: copy.templates.targetGoalHint,
    };
  }

  function renderComposition(simulation) {
    const initialAmount = Math.max(0, simulation.totalInvested - simulation.periodicContributions);
    const gains = Math.max(0, simulation.totalInterest);
    const losses = Math.max(0, -simulation.totalInterest);
    const compositionBase =
      initialAmount + simulation.periodicContributions + gains + losses || 1;

    const principalWidth = (initialAmount / compositionBase) * 100;
    const contributionWidth = (simulation.periodicContributions / compositionBase) * 100;
    const interestWidth = (gains / compositionBase) * 100;
    const lossWidth = (losses / compositionBase) * 100;

    principalSegment.style.width = `${principalWidth}%`;
    contributionSegment.style.width = `${contributionWidth}%`;
    interestSegment.style.width = `${interestWidth}%`;
    lossSegment.style.width = `${lossWidth}%`;

    principalLegend.textContent = formatCurrency(initialAmount);
    contributionLegend.textContent = formatCurrency(simulation.periodicContributions);
    interestLegend.textContent = formatCurrency(gains);
    lossLegend.textContent = formatCurrency(losses);
    lossLegendItem.hidden = losses === 0;
    compositionMeta.textContent =
      losses === 0
        ? copy.templates.compositionPositive({
            endingBalance: formatCurrency(simulation.endingBalance),
          })
        : copy.templates.compositionNegative({
            totalInvested: formatCurrency(simulation.totalInvested),
            endingBalance: formatCurrency(simulation.endingBalance),
          });
  }

  function renderChart(simulation) {
    const rows = simulation.yearRows || [];
    const initialAmount = Math.max(0, simulation.totalInvested - simulation.periodicContributions);

    if (!rows.length) {
      growthChart.innerHTML = "";
      chartLegend.innerHTML = "";
      chartEmpty.hidden = false;
      return;
    }

    chartEmpty.hidden = true;

    const width = 720;
    const height = 280;
    const padding = { top: 16, right: 10, bottom: 34, left: 58 };
    const innerWidth = width - padding.left - padding.right;
    const innerHeight = height - padding.top - padding.bottom;
    let cumulativeContributions = 0;
    let cumulativeInterest = 0;
    const series = rows.map((row, index) => {
      cumulativeContributions += row.contribution;
      cumulativeInterest += row.interest;
      return {
        index,
        yearLabel: row.label,
        yearNumber: row.yearsElapsed,
        principal: initialAmount,
        contributions: cumulativeContributions,
        interest: cumulativeInterest,
        endingBalance: row.endingBalance,
        invested: initialAmount + cumulativeContributions,
      };
    });

    const rawMaxValue = Math.max(
      ...series.map((item) => Math.max(item.endingBalance, item.invested)),
      1
    );
    const gridSteps = 4;
    const stepValue = getNiceStep(rawMaxValue / gridSteps);
    const maxValue = stepValue * gridSteps;
    const barSlotWidth = innerWidth / series.length;
    const barWidth = Math.max(10, Math.min(34, barSlotWidth * 0.58));
    const xLabelInterval = Math.max(1, Math.ceil(series.length / 8));
    const yForValue = (value) =>
      padding.top + innerHeight - (value / maxValue) * innerHeight;

    const gridMarkup = Array.from({ length: gridSteps + 1 }, function (_, index) {
      const value = stepValue * index;
      const y = yForValue(value);
      return `
        <line x1="${padding.left}" y1="${y.toFixed(2)}" x2="${width - padding.right}" y2="${y.toFixed(2)}" stroke="rgba(34, 75, 59, 0.12)" stroke-width="1" />
        <text x="${padding.left - 8}" y="${(y + 4).toFixed(2)}" text-anchor="end" fill="rgba(83, 98, 87, 0.82)" font-size="11">${formatCurrencyCompact(value)}</text>
      `;
    }).join("");

    const barsMarkup = series
      .map((item) => {
        const x = padding.left + barSlotWidth * item.index + (barSlotWidth - barWidth) / 2;
        const principalTop = yForValue(item.principal);
        const contributionsTop = yForValue(item.principal + item.contributions);
        const endingTop = yForValue(item.endingBalance);
        const investedTop = yForValue(item.invested);
        const principalHeight = yForValue(0) - principalTop;
        const contributionsHeight = principalTop - contributionsTop;
        const interestHeight = Math.abs(investedTop - endingTop);
        const xLabel =
          Number.isInteger(item.yearNumber) && item.yearNumber > 0
            ? String(item.yearNumber)
            : numberFormatter.format(item.yearNumber);

        const interestRect =
          interestHeight > 0
            ? `<rect x="${x.toFixed(2)}" y="${Math.min(endingTop, investedTop).toFixed(2)}" width="${barWidth.toFixed(2)}" height="${interestHeight.toFixed(2)}" rx="3" fill="#a20b0b"></rect>`
            : "";
        const shouldRenderLabel =
          item.index === 0 ||
          item.index === series.length - 1 ||
          (item.index + 1) % xLabelInterval === 0;

        return `
          <rect x="${x.toFixed(2)}" y="${principalTop.toFixed(2)}" width="${barWidth.toFixed(2)}" height="${principalHeight.toFixed(2)}" rx="3" fill="#2e73d1"></rect>
          <rect x="${x.toFixed(2)}" y="${contributionsTop.toFixed(2)}" width="${barWidth.toFixed(2)}" height="${contributionsHeight.toFixed(2)}" rx="3" fill="#8cc21b"></rect>
          ${interestRect}
          ${
            shouldRenderLabel
              ? `<text x="${(x + barWidth / 2).toFixed(2)}" y="${(height - 12).toFixed(2)}" text-anchor="middle" fill="rgba(83, 98, 87, 0.82)" font-size="11">${xLabel}</text>`
              : ""
          }
        `;
      })
      .join("");

    growthChart.innerHTML = `
      ${gridMarkup}
      <line x1="${padding.left}" y1="${(height - padding.bottom).toFixed(2)}" x2="${width - padding.right}" y2="${(height - padding.bottom).toFixed(2)}" stroke="rgba(83, 98, 87, 0.4)" stroke-width="1.2"></line>
      ${barsMarkup}
    `;

    chartLegend.innerHTML = `
      <div class="chart-legend__item">
        <span class="chart-legend__swatch chart-legend__swatch--principal"></span>
        <span>${copy.chart.legend.principal}</span>
      </div>
      <div class="chart-legend__item">
        <span class="chart-legend__swatch chart-legend__swatch--contributions"></span>
        <span>${copy.chart.legend.contributions}</span>
      </div>
      <div class="chart-legend__item">
        <span class="chart-legend__swatch chart-legend__swatch--interest"></span>
        <span>${copy.chart.legend.interest}</span>
      </div>
    `;
  }

  function getNiceStep(value) {
    if (!Number.isFinite(value) || value <= 0) {
      return 1;
    }

    const magnitude = Math.pow(10, Math.floor(Math.log10(value)));
    const normalized = value / magnitude;

    if (normalized <= 1) {
      return 1 * magnitude;
    }
    if (normalized <= 2) {
      return 2 * magnitude;
    }
    if (normalized <= 2.5) {
      return 2.5 * magnitude;
    }
    if (normalized <= 5) {
      return 5 * magnitude;
    }
    return 10 * magnitude;
  }

  function renderTable(rows, durationLabel, endingBalance) {
    const safeRows = rows.length
      ? rows
      : [
          {
            label: `${copy.periodTokens.year} 0`,
            contribution: 0,
            interest: 0,
            endingBalance,
          },
        ];

    scheduleBody.innerHTML = safeRows
      .map(
        (row) => `
          <tr>
            <td>${row.label}</td>
            <td>${formatCurrency(row.contribution)}</td>
            <td>${formatCurrency(row.interest)}</td>
            <td>${formatCurrency(row.endingBalance)}</td>
          </tr>
        `
      )
      .join("");

    tableSummary.textContent = copy.templates.tableSummary({
      count: safeRows.length,
      durationLabel,
    });
  }

  function showError(message) {
    errorBox.hidden = false;
    errorBox.textContent = message;
  }

  function hideError() {
    errorBox.hidden = true;
    errorBox.textContent = "";
  }

  function updateMode(nextMode) {
    currentMode = nextMode;
    modeSelect.value = nextMode;

    const hiddenFields = new Set(modeConfig[nextMode].hiddenFields);
    Object.entries(fieldGroups).forEach(([groupKey, group]) => {
      group.classList.toggle("is-hidden", hiddenFields.has(groupKey));
    });

    modeHelper.textContent = copy.modes[nextMode].helper;
    if (window.__setFormulaMode) window.__setFormulaMode(nextMode);
    calculateAndRender();
  }

  function calculateAndRender() {
    try {
      const inputs = collectInputs();
      const scenario = solveScenario(inputs);
      renderScenario(inputs, scenario);
    } catch (error) {
      showError(error instanceof Error ? error.message : copy.errors.generic);
    }
  }

  modeSelect.addEventListener("change", function () {
    updateMode(modeSelect.value);
  });

  form.addEventListener("submit", function (event) {
    event.preventDefault();
    calculateAndRender();
  });

  form.addEventListener("input", function () {
    calculateAndRender();
  });

  updateMode(currentMode);
})();

(function () {
  const formulas = {
    primary: {
      endBalance: {
        title: "Ending Balance",
        formula: "FV = PV × (1 + r)ⁿ\n    + PMT × [((1 + r)ⁿ − 1) / r]",
        vars: ["PV = initial capital", "r = rate per period", "n = total periods", "PMT = periodic contribution"],
      },
      contribution: {
        title: "Required Periodic Contribution",
        formula: "PMT = (FV − PV × (1+r)ⁿ) × r\n    / ((1+r)ⁿ − 1)",
        vars: ["FV = target amount", "PV = initial capital", "r = rate per period", "n = total periods"],
      },
      rate: {
        title: "Required Rate",
        formula: "Solved by numerical bisection\nover the future value formula",
        vars: ["FV = target amount", "PV = initial capital", "PMT = periodic contribution", "n = total periods"],
      },
      startingAmount: {
        title: "Recommended Starting Amount",
        formula: "PV = (FV − PMT × [((1+r)ⁿ − 1) / r])\n    / (1+r)ⁿ",
        vars: ["FV = target amount", "r = rate per period", "n = total periods", "PMT = periodic contribution"],
      },
      length: {
        title: "Estimated Time",
        formula: "n = log((FV + PMT/r) / (PV + PMT/r))\n    / log(1 + r)",
        vars: ["FV = target amount", "PV = initial capital", "r = rate per period", "PMT = periodic contribution"],
      },
    },
    invested: {
      title: "Total Capital Invested",
      formula: "TC = PV + (PMT × n)",
      vars: ["PV = initial capital", "PMT = periodic contribution", "n = total periods"],
    },
    interest: {
      title: "Net Interest",
      formula: "I = FV − TC",
      vars: ["FV = ending balance (future value)", "TC = total capital invested"],
    },
    secondary: {
      title: "Effective Annual Return",
      formula: "EAR = (1 + r / m)ᵐ − 1\n\nContinuous compounding:\nEAR = eʳ − 1",
      vars: ["r = nominal annual rate", "m = compounding frequency", "e = Euler's number (≈ 2.71828)"],
    },
    ariaLabel: "View formula",
  };

  let currentTooltipMode = "endBalance";
  const tooltip = document.getElementById("formulaTooltip");
  const tooltipTitle = document.getElementById("formulaTooltipTitle");
  const tooltipFormula = document.getElementById("formulaTooltipFormula");
  const tooltipVars = document.getElementById("formulaTooltipVars");
  const tooltipClose = document.getElementById("formulaTooltipClose");
  const helpBtns = document.querySelectorAll(".metric-help-btn");
  let activeBtn = null;

  function getFormulaFor(metric) {
    if (metric === "primary") return formulas.primary[currentTooltipMode] || formulas.primary.endBalance;
    return formulas[metric];
  }

  function showTooltip(btn, metric) {
    const data = getFormulaFor(metric);
    if (!data) return;

    tooltipTitle.textContent = data.title;
    tooltipFormula.textContent = data.formula;
    tooltipVars.innerHTML = data.vars.map((v) => `<span>${v}</span>`).join("");

    tooltip.classList.add("is-visible");
    positionTooltip(btn);
    activeBtn = btn;
  }

  function positionTooltip(btn) {
    const rect = btn.getBoundingClientRect();
    const TW = 300;
    const margin = 8;
    let left = rect.right - TW;
    if (left < margin) left = margin;
    if (left + TW > window.innerWidth - margin) left = window.innerWidth - TW - margin;
    let top = rect.bottom + 6;
    if (top + tooltip.offsetHeight > window.innerHeight - margin) {
      top = rect.top - tooltip.offsetHeight - 6;
    }
    tooltip.style.left = left + "px";
    tooltip.style.top = top + "px";
  }

  function hideTooltip() {
    tooltip.classList.remove("is-visible");
    activeBtn = null;
  }

  document.querySelectorAll(".metric-help-btn").forEach(function (btn) {
    btn.addEventListener("click", function () {
      if (activeBtn === btn) {
        hideTooltip();
      } else {
        showTooltip(btn, btn.dataset.metric);
      }
    });
  });

  tooltipClose.addEventListener("click", hideTooltip);

  document.addEventListener("mousedown", function (e) {
    if (!tooltip.classList.contains("is-visible")) return;
    if (tooltip.contains(e.target)) return;
    if (e.target.closest(".metric-help-btn")) return;
    hideTooltip();
  });

  document.addEventListener("keydown", function (e) {
    if (e.key === "Escape") hideTooltip();
  });

  window.addEventListener("scroll", function () {
    if (activeBtn && tooltip.classList.contains("is-visible")) {
      positionTooltip(activeBtn);
    }
  }, { passive: true });

  window.__setFormulaMode = function (mode) {
    currentTooltipMode = mode;
  };

  helpBtns.forEach(function (btn) {
    btn.setAttribute("aria-label", formulas.ariaLabel);
  });
})();
