const mineralData={sodium:{name:"Sodium + chloride",image:"../../assets/imgs/hydration-cards/Na.png",mg:810,color:"#a9d9df"},potassium:{name:"Potassium",image:"../../assets/imgs/hydration-cards/K.png",mg:400,color:"#e8c77a"},magnesium:{name:"Magnesium",image:"../../assets/imgs/hydration-cards/Mg.png",mg:50,color:"#c9a7df"},calcium:{name:"Calcium",image:"../../assets/imgs/hydration-cards/Ca.png",mg:60,color:"#f1eee0"}};
const dangerData={sugar:{name:"Sugar",image:"assets/generated/sugar.png"},coloring:{name:"Artificial coloring",image:"assets/generated/coloring.png"},kryptonite:{name:"Kryptonite",image:"assets/generated/kryptonite.png"},glitter:{name:"Glitter",image:"assets/generated/glitter.png"},hotSauce:{name:"Hot sauce",image:"assets/generated/hot-sauce.png"},motorOil:{name:"Motor oil",image:"assets/generated/motor-oil.png"}};
const dangerColors={sugar:"#d9b44a",coloring:"#ef6b92",kryptonite:"#82d62f",glitter:"#d9a7ff",hotSauce:"#e55232",motorOil:"#39434d"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const r={instruction:$("#instruction"),score:$("#score"),stage:$("#mix-stage"),stageLabel:$("#stage-label"),bottle:$("#bottle"),bottleLabel:$("#bottle-label"),bottleMolecules:$("#bottle-molecules"),water:$("#water-btn"),shake:$("#shake-btn"),shakeFill:$("#shake-fill"),shakeCount:$("#shake-count"),toast:$("#toast"),particles:$("#particles"),spill:$("#spill-effect"),complete:$("#complete"),completeCopy:$("#complete-copy"),finalScore:$("#final-score"),gameOver:$("#game-over"),gameOverCopy:$("#game-over-copy")};
let state,timer,explosionTimer,modalTimer,pointerStart,suppressClick=false;
const fresh=()=>({open:false,water:false,minerals:{sodium:false,potassium:false,magnesium:false,calcium:false},sealed:false,shakes:0,complete:false,gameOver:false,contaminatedIngredients:[],mistakes:0});
const mineralsComplete=()=>Object.values(state.minerals).every(Boolean);
function dangerMixColor(){const ids=state.contaminatedIngredients||[];if(!ids.length)return null;const rgb=ids.map(id=>(dangerColors[id]||"#8ed33d").match(/../g).map(x=>parseInt(x,16)));return"#"+[0,1,2].map(i=>Math.round(rgb.reduce((s,v)=>s+v[i],0)/rgb.length).toString(16).padStart(2,"0")).join("")}
function mixColor(){let r0=218,g0=241,b0=246,total=120;Object.values(mineralData).forEach(m=>{if(state.minerals[Object.keys(mineralData).find(k=>mineralData[k]===m)]){const h=m.color.slice(1),w=m.mg;r0+=(parseInt(h.slice(0,2),16)*w);g0+=(parseInt(h.slice(2,4),16)*w);b0+=(parseInt(h.slice(4,6),16)*w);total+=w}});return`#${[r0,g0,b0].map(v=>Math.round(v/total).toString(16).padStart(2,"0")).join("")}`}
function phase(){if(!state.open&&!state.water)return"open";if(!state.water)return"fill";if(!mineralsComplete())return"choose";if(!state.sealed)return"close";return"shake"}
function toast(message,bad=false){r.toast.textContent=message;r.toast.className=`toast show${bad?" bad":""}`;clearTimeout(timer);timer=setTimeout(()=>r.toast.className="toast",1800)}
function check(name,done){const el=$(`[data-check="${name}"]`);if(el)el.classList.toggle("done",done)}
function burst(){r.particles.innerHTML="";for(let i=0;i<28;i++){const d=document.createElement("i");d.style.setProperty("--x",`${10+Math.random()*80}%`);d.style.setProperty("--delay",`${Math.random()*.35}s`);d.style.setProperty("--color",i%2?"#d8ecea":"#fff");r.particles.append(d)}setTimeout(()=>r.particles.innerHTML="",1800)}
function render(){
  const p=phase(),added=Object.values(state.minerals).filter(Boolean).length,locked=state.complete||state.gameOver;
  const liquidColor=dangerMixColor()||mixColor();r.stage.style.setProperty("--flavor",liquidColor);r.stage.style.setProperty("--flavor-deep",liquidColor);
  r.bottle.classList.toggle("open",state.open);r.bottle.classList.toggle("has-water",state.water);r.bottle.classList.toggle("has-powder",added>0||state.contaminatedIngredients.length>0);r.bottle.classList.toggle("mixed",state.complete);
  r.water.disabled=!state.open||state.water||locked;
  $$('.mineral-btn').forEach(b=>{const id=b.dataset.mineral,danger=b.dataset.danger;b.disabled=!state.open||!state.water||(id&&state.minerals[id])||(danger&&state.contaminatedIngredients.includes(danger))||locked;if(id)b.classList.toggle('used',state.minerals[id]);if(danger)b.classList.toggle('used',state.contaminatedIngredients.includes(danger))});
  r.shake.disabled=!state.sealed||locked;r.shakeFill.style.width=`${state.shakes*20}%`;r.shakeCount.textContent=`${state.shakes} / 5`;
  check("water",state.water);Object.keys(mineralData).forEach(id=>check(id,state.minerals[id]));check("sealed",state.sealed);check("shaken",state.complete);
  const order=["open","fill","choose","close","shake"],now=order.indexOf(p);$$('.steps li').forEach(s=>{const n=order.indexOf(s.dataset.step);s.classList.toggle("active",n===now&&!locked);s.classList.toggle("done",n<now||state.complete)});
  r.bottleLabel.innerHTML=`CUSTOM<br><small>${added}/4 MINERALS</small>`;
  const remaining=4-added,copy={open:["Open the bottle","Tap the black lid to twist it open.","Step 1 of 5"],fill:["Add cold water first","Fill the bottle to the 16 oz line.","Step 2 of 5"],choose:["Choose the minerals",`Find and add ${remaining} remaining essential mineral${remaining===1?"":"s"}. Avoid the impostors.`,"Step 3 of 5"],close:["Seal it tight","Tap the lid to close the bottle before shaking.","Step 4 of 5"],shake:["Shake it up","Shake five times until everything dissolves.","Step 5 of 5"]}[p];
  r.stageLabel.textContent=state.gameOver?"The mix became unstable!":copy[0];r.instruction.textContent=state.gameOver?"Wrong ingredient—game over.":copy[1];r.score.textContent=state.gameOver?0:Math.max(0,100-state.mistakes*10+state.shakes*4);
}
function toggleLid(){if(suppressClick){suppressClick=false;return}if(state.complete||state.gameOver)return;if(state.open){if(!state.water)return toast("Add cold water before closing.",true);if(!mineralsComplete()){state.mistakes++;toast("Add all four essential minerals before sealing.",true);return render()}state.open=false;state.sealed=true;toast("Click—sealed tight!")}else{if(state.sealed&&state.shakes)return toast("Keep it sealed while mixing.",true);state.open=true;toast("Lid open. Add water first.")}render()}
function addWater(){if(!state.open||state.gameOver)return;state.water=true;r.bottle.classList.add("pouring");toast("16 oz of cold water added");setTimeout(()=>r.bottle.classList.remove("pouring"),800);render()}
function putMoleculeInside(id){const img=document.createElement("img");img.src=mineralData[id].image;img.alt="";img.className=`molecule-inside molecule-${id}`;img.style.setProperty("--float-delay",`${Math.random()*-.8}s`);r.bottleMolecules.append(img)}
function putDangerInside(id){const img=document.createElement("img");img.src=dangerData[id].image;img.alt="";img.className=`molecule-inside molecule-danger molecule-${id}`;img.style.setProperty("--float-delay",`${Math.random()*-.8}s`);img.style.left=`${12+Math.random()*68}%`;img.style.bottom=`${8+Math.random()*58}%`;img.style.width=`${34+Math.random()*20}px`;img.style.height=`${34+Math.random()*20}px`;img.style.rotate=`${-18+Math.random()*36}deg`;r.bottleMolecules.append(img)}
function flyMineral(id,button){const source=button.querySelector("img, span"),start=source.getBoundingClientRect(),mouth=r.bottle.querySelector(".neck").getBoundingClientRect(),fly=source.cloneNode(true),x=mouth.left+mouth.width/2-start.left-start.width/2,y=mouth.top+mouth.height/2-start.top-start.height/2;fly.className="flying-molecule";fly.style.left=`${start.left+start.width/2}px`;fly.style.top=`${start.top+start.height/2}px`;fly.style.setProperty("--fly-x",`${x}px`);fly.style.setProperty("--fly-y",`${y}px`);fly.style.setProperty("--fly-mid-x",`${x*.46}px`);fly.style.setProperty("--fly-mid-y",`${y*.32-80}px`);fly.style.setProperty("--fly-near-x",`${x*.9}px`);fly.style.setProperty("--fly-near-y",`${y*.86}px`);document.body.append(fly);fly.addEventListener("animationend",()=>{fly.remove();if(mineralData[id]&&!state.gameOver)putMoleculeInside(id);if(dangerData[id]&&!state.gameOver)putDangerInside(id)},{once:true})}
function spawnDebris(){const colors=["#b9d8d5","#e9f6ee","#5e888b","#d7eee5","#86b5b2"];for(let i=0;i<24;i++){const f=document.createElement("i");f.className="bottle-fragment";f.style.left="50%";f.style.top="47%";f.style.setProperty("--dx",`${(Math.random()-.5)*Math.min(innerWidth*.9,760)}px`);f.style.setProperty("--dy",`${(Math.random()-.7)*Math.min(innerHeight*.9,620)}px`);f.style.setProperty("--rot",`${(Math.random()-.5)*900}deg`);f.style.setProperty("--size",`${5+Math.random()*15}px`);f.style.setProperty("--tone",colors[i%colors.length]);r.spill.append(f)}setTimeout(()=>$$('.bottle-fragment').forEach(f=>f.remove()),4800)}
function playExplosionSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),t=c.currentTime,o=c.createOscillator(),g=c.createGain(),n=c.createBufferSource(),b=c.createBuffer(1,c.sampleRate*.55,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);o.type="sawtooth";o.frequency.setValueAtTime(120,t);o.frequency.exponentialRampToValueAtTime(42,t+.42);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.7,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+.62);n.buffer=b;const ng=c.createGain();ng.gain.setValueAtTime(.001,t);ng.gain.exponentialRampToValueAtTime(.8,t+.015);ng.gain.exponentialRampToValueAtTime(.001,t+.55);o.connect(g).connect(c.destination);n.connect(ng).connect(c.destination);o.start(t);o.stop(t+.65);n.start(t);n.stop(t+.56);setTimeout(()=>c.close(),900)}catch(e){}}
function addMineral(id,button){if(!state.open||!state.water||state.gameOver)return;state.minerals[id]=true;flyMineral(id,button);r.bottle.classList.add("dusting");toast(`${mineralData[id].name} added`);setTimeout(()=>r.bottle.classList.remove("dusting"),650);render()}
function triggerExplosion(ids){const names=ids.map(id=>dangerData[id].name),mixed=dangerMixColor();state.gameOver=true;state.open=false;r.stage.style.setProperty("--spill-color",mixed);r.gameOver.style.setProperty("background",mixed,"important");r.gameOver.style.setProperty("--spill-color",mixed);r.spill.style.setProperty("--spill-color",mixed);r.bottle.classList.add("radioactive");toast("Unstable ingredients triggered a reaction!",true);render();explosionTimer=setTimeout(()=>{playExplosionSound();spawnDebris();r.bottle.classList.add("exploding");r.spill.classList.add("show");r.spill.setAttribute("aria-hidden","false")},360);modalTimer=setTimeout(()=>{r.spill.classList.remove("show");r.spill.setAttribute("aria-hidden","true");r.gameOverCopy.textContent=`${names.join(", ")} do not belong in the mineral profile. The unstable mix broke the bottle and spilled everywhere.`;r.gameOver.classList.add("show");r.gameOver.setAttribute("aria-hidden","false")},3360)}
function addDanger(id,button){if(!state.open||!state.water||state.gameOver||state.contaminatedIngredients.includes(id))return;state.contaminatedIngredients.push(id);const mixed=dangerMixColor();r.stage.style.setProperty("--spill-color",mixed);r.stage.style.setProperty("--flavor",mixed);r.stage.style.setProperty("--flavor-deep",mixed);flyMineral(id,button);toast("Ingredient added.");render()}
function shake(){if(!state.sealed||state.complete||state.gameOver)return toast("Seal the lid before shaking.",true);if(state.contaminatedIngredients.length)return triggerExplosion(state.contaminatedIngredients);state.shakes++;r.bottle.classList.remove("shaking");void r.bottle.offsetWidth;r.bottle.classList.add("shaking");setTimeout(()=>r.bottle.classList.remove("shaking"),720);if(state.shakes>=5){state.shakes=5;state.complete=true;burst();setTimeout(()=>{r.complete.classList.add("show");r.complete.setAttribute("aria-hidden","false")},760);r.completeCopy.textContent="You measured four separate minerals to build the electrolyte profile—the hard way.";r.finalScore.textContent=Math.max(0,120-state.mistakes*10)}render()}
function shuffleIngredients(){const dock=$(".mineral-dock"),items=[...dock.children];for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}items.forEach(item=>dock.append(item))}
function reset(){clearTimeout(explosionTimer);clearTimeout(modalTimer);state=fresh();shuffleIngredients();r.bottleMolecules.innerHTML="";$$('.flying-molecule').forEach(el=>el.remove());r.bottle.classList.remove("radioactive","exploding");r.spill.classList.remove("show");r.spill.setAttribute("aria-hidden","true");r.gameOver.style.removeProperty("background");[r.complete,r.gameOver].forEach(card=>{card.classList.remove("show");card.setAttribute("aria-hidden","true")});render()}
$$('.mineral-btn[data-mineral]').forEach(b=>b.addEventListener('click',()=>addMineral(b.dataset.mineral,b)));$$('.mineral-btn[data-danger]').forEach(b=>b.addEventListener('click',()=>addDanger(b.dataset.danger,b)));r.bottle.addEventListener('click',toggleLid);r.water.addEventListener('click',addWater);r.shake.addEventListener('click',shake);r.bottle.addEventListener('pointerdown',e=>pointerStart=e.clientX);r.bottle.addEventListener('pointerup',e=>{if(pointerStart!==undefined&&Math.abs(e.clientX-pointerStart)>45&&state.sealed){suppressClick=true;shake()}pointerStart=undefined});$('#reset-btn').addEventListener('click',reset);$('#mix-another').addEventListener('click',reset);$('#retry-btn').addEventListener('click',reset);reset();
