// Flavor colors are intentionally very soft: Re-Lyte has no artificial colors,
// so these tints are only a subtle visual cue for the game.
const flavors={lemon:{name:"Lemon Lime",color:"#edf0c9",deep:"#dde3b1"},strawberry:{name:"Strawberry Lemonade",color:"#f6dce1",deep:"#edc7d0"},mango:{name:"Mango",color:"#f8e5c9",deep:"#efd4af"}};
const mineralData={sodium:{name:"Sodium + chloride",image:"../../assets/imgs/hydration-cards/Na.png"},potassium:{name:"Potassium",image:"../../assets/imgs/hydration-cards/K.png"},magnesium:{name:"Magnesium",image:"../../assets/imgs/hydration-cards/Mg.png"},calcium:{name:"Calcium",image:"../../assets/imgs/hydration-cards/Ca.png"}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const r={instruction:$("#instruction"),score:$("#score"),title:$("#recipe-title"),status:$("#recipe-status"),stage:$("#mix-stage"),stageLabel:$("#stage-label"),bottle:$("#bottle"),bottleLabel:$("#bottle-label"),bottleMolecules:$("#bottle-molecules"),water:$("#water-btn"),powder:$("#powder-btn"),shake:$("#shake-btn"),shakeFill:$("#shake-fill"),shakeCount:$("#shake-count"),toast:$("#toast"),particles:$("#particles"),complete:$("#complete"),completeCopy:$("#complete-copy"),finalScore:$("#final-score"),help:$("#help-dialog"),flavorWrap:$("#flavor-wrap")};
let state,timer,pointerStart,suppressClick=false;
const fresh=()=>({method:null,flavor:null,open:false,water:false,powder:false,minerals:{sodium:false,potassium:false,magnesium:false,calcium:false},sealed:false,shakes:0,complete:false,mistakes:0});
const mineralsComplete=()=>Object.values(state.minerals).every(Boolean);
const ingredientsComplete=()=>state.water&&(state.method==="relyte"?state.powder:mineralsComplete());
function phase(){if(!state.method||(state.method==="relyte"&&!state.flavor))return"flavor";if(!state.open&&!state.water)return"open";if(!ingredientsComplete())return"fill";if(!state.sealed)return"close";return"shake"}
function toast(message,bad=false){r.toast.textContent=message;r.toast.className=`toast show${bad?" bad":""}`;clearTimeout(timer);timer=setTimeout(()=>r.toast.className="toast",1800)}
function check(name,done){const el=$(`[data-check="${name}"]`);if(el)el.classList.toggle("done",done)}
function burst(){r.particles.innerHTML="";for(let i=0;i<28;i++){const d=document.createElement("i");d.style.setProperty("--x",`${10+Math.random()*80}%`);d.style.setProperty("--delay",`${Math.random()*.35}s`);d.style.setProperty("--color",i%2?r.stage.style.getPropertyValue("--flavor"):"#fff");r.particles.append(d)}setTimeout(()=>r.particles.innerHTML="",1800)}
function render(){const p=phase(),recipe=state.flavor&&flavors[state.flavor],custom=state.method==="minerals",added=Object.values(state.minerals).filter(Boolean).length;r.stage.style.setProperty("--flavor",custom?"#d8ecea":recipe?.color||"#e8f2f3");r.stage.style.setProperty("--flavor-deep",custom?"#c3dfdd":recipe?.deep||"#d4e7e9");r.bottle.classList.toggle("open",state.open);r.bottle.classList.toggle("has-water",state.water);r.bottle.classList.toggle("has-powder",state.powder||added>0);r.bottle.classList.toggle("mixed",state.complete);r.water.disabled=!state.open||state.water||state.complete;r.powder.disabled=!state.open||!state.water||state.powder||state.complete;$$('.mineral-btn').forEach(b=>{b.disabled=!state.open||!state.water||state.minerals[b.dataset.mineral]||state.complete;b.classList.toggle('used',state.minerals[b.dataset.mineral])});r.shake.disabled=!state.sealed||state.complete;r.shakeFill.style.width=`${state.shakes*20}%`;r.shakeCount.textContent=`${state.shakes} / 5`;check("water",state.water);check("powder",state.powder);Object.keys(mineralData).forEach(id=>check(id,state.minerals[id]));check("sealed",state.sealed);check("shaken",state.complete);document.body.dataset.method=state.method||"none";r.flavorWrap.classList.toggle("show",state.method==="relyte");$$('.method').forEach(b=>b.classList.toggle('selected',b.dataset.method===state.method));$$('.flavor').forEach(b=>b.classList.toggle('selected',b.dataset.flavor===state.flavor));
const order=["flavor","open","fill","close","shake"],now=order.indexOf(p);$$('.steps li').forEach(s=>{const n=order.indexOf(s.dataset.step);s.classList.toggle("active",n===now);s.classList.toggle("done",n<now||state.complete)});
if(!state.method){r.title.textContent="Choose your method";r.status.textContent="Not started";r.stageLabel.textContent="How will you build the mix?";r.instruction.textContent="Choose Re-Lyte for the simple route or build the same electrolyte profile mineral by mineral.";r.bottleLabel.innerHTML="CHOOSE<br>A METHOD"}
else if(state.method==="relyte"&&!recipe){r.title.textContent="Use Re-Lyte";r.status.textContent="Choose flavor";r.stageLabel.textContent="Choose your Re-Lyte flavor";r.instruction.textContent="Choose a flavor, then prepare the bottle with one scoop.";r.bottleLabel.innerHTML="CHOOSE<br>A FLAVOR"}
else{const name=custom?"Mineral Challenge":recipe.name;r.title.textContent=name;r.bottleLabel.innerHTML=custom?`CUSTOM<br><small>4 MINERALS</small>`:`RE-LYTE<br><small>${recipe.name.toUpperCase()}</small>`;const remaining=4-added;const copy={open:["Open the bottle","Tap the black lid to twist it open.","Step 2 of 5"],fill:[!state.water?"Add cold water first":custom?"Build the mineral profile":"Add one Re-Lyte scoop",!state.water?"Fill the bottle to the 16 oz line.":custom?`Find and add ${remaining} remaining mineral${remaining===1?"":"s"}.`:"One scoop contains the complete electrolyte profile.","Step 3 of 5"],close:["Seal it tight","Tap the lid to close the bottle before shaking.","Step 4 of 5"],shake:["Shake it up","Shake five times until everything dissolves.","Step 5 of 5"]}[p];r.stageLabel.textContent=copy[0];r.instruction.textContent=copy[1];r.status.textContent=state.complete?"Ready":copy[2]}r.score.textContent=Math.max(0,100-state.mistakes*10+state.shakes*4)}
function chooseMethod(method){if(state.water)return toast("Start over to change methods after filling.",true);state.method=method;state.flavor=null;toast(method==="relyte"?"Simple route selected":"Mineral challenge selected");render()}
function chooseFlavor(id){if(state.method!=="relyte")return;if(state.water)return toast("Start over to change flavor after filling.",true);state.flavor=id;toast(`${flavors[id].name} selected`);render()}
function toggleLid(){if(suppressClick){suppressClick=false;return}if(!state.method||(state.method==="relyte"&&!state.flavor))return toast("Choose your mix first.",true);if(state.complete)return;if(state.open){if(!ingredientsComplete()){state.mistakes++;toast(state.method==="minerals"?"Add all four minerals before sealing.":"Add the Re-Lyte scoop before sealing.",true);return render()}state.open=false;state.sealed=true;toast("Click—sealed tight!")}else{if(state.sealed&&state.shakes)return toast("Keep it sealed while mixing.",true);state.open=true;toast("Lid open. Add water first.")}render()}
function addWater(){if(!state.open)return;state.water=true;r.bottle.classList.add("pouring");toast("16 oz of cold water added");setTimeout(()=>r.bottle.classList.remove("pouring"),800);render()}
function animateScoop(){const source=r.powder.querySelector(".scoop-icon"),start=source.getBoundingClientRect(),mouth=r.bottle.querySelector(".neck").getBoundingClientRect(),scoop=document.createElement("span"),x=mouth.left+mouth.width/2-start.left-start.width/2,y=mouth.top+mouth.height/2-start.top-start.height/2;scoop.className="flying-scoop";scoop.style.left=`${start.left+start.width/2}px`;scoop.style.top=`${start.top+start.height/2}px`;scoop.style.setProperty("--scoop-x",`${x}px`);scoop.style.setProperty("--scoop-y",`${y}px`);scoop.style.setProperty("--flavor",flavors[state.flavor].color);scoop.innerHTML=`<i class="scoop-handle"></i><i class="scoop-bowl"></i><span class="scoop-powder">${"<b></b>".repeat(10)}</span>`;document.body.append(scoop);setTimeout(()=>r.bottle.classList.add("dusting"),640);scoop.addEventListener("animationend",event=>{if(event.target===scoop){scoop.remove();r.bottle.classList.remove("dusting")}},{once:true})}
function addPowder(){if(!state.open||!state.water)return;state.powder=true;animateScoop();toast("One complete Re-Lyte scoop added");render()}
function putMoleculeInside(id){const img=document.createElement("img");img.src=mineralData[id].image;img.alt="";img.className=`molecule-inside molecule-${id}`;img.style.setProperty("--float-delay",`${Math.random()*-.8}s`);r.bottleMolecules.append(img)}
function flyMineral(id,button){const source=button.querySelector("img"),start=source.getBoundingClientRect(),mouth=r.bottle.querySelector(".neck").getBoundingClientRect(),fly=source.cloneNode(),x=mouth.left+mouth.width/2-start.left-start.width/2,y=mouth.top+mouth.height/2-start.top-start.height/2;fly.className="flying-molecule";fly.style.left=`${start.left+start.width/2}px`;fly.style.top=`${start.top+start.height/2}px`;fly.style.setProperty("--fly-x",`${x}px`);fly.style.setProperty("--fly-y",`${y}px`);fly.style.setProperty("--fly-mid-x",`${x*.46}px`);fly.style.setProperty("--fly-mid-y",`${y*.32-80}px`);fly.style.setProperty("--fly-near-x",`${x*.9}px`);fly.style.setProperty("--fly-near-y",`${y*.86}px`);document.body.append(fly);fly.addEventListener("animationend",()=>{fly.remove();putMoleculeInside(id)},{once:true})}
function addMineral(id,button){if(!state.open||!state.water||state.method!=="minerals")return;state.minerals[id]=true;flyMineral(id,button);r.bottle.classList.add("dusting");toast(`${mineralData[id].name} added`);setTimeout(()=>r.bottle.classList.remove("dusting"),650);render()}
function shake(){if(!state.sealed||state.complete)return toast("Seal the lid before shaking.",true);state.shakes++;r.bottle.classList.remove("shaking");void r.bottle.offsetWidth;r.bottle.classList.add("shaking");setTimeout(()=>r.bottle.classList.remove("shaking"),720);if(state.shakes>=5){state.shakes=5;state.complete=true;burst();setTimeout(()=>{r.complete.classList.add("show");r.complete.setAttribute("aria-hidden","false")},760);r.completeCopy.textContent=state.method==="relyte"?`One scoop delivered the complete electrolyte profile. Your ${flavors[state.flavor].name} Re-Lyte is ready.`:"You measured four separate minerals to build the electrolyte profile. Re-Lyte combines this job into one simple scoop.";r.finalScore.textContent=Math.max(0,120-state.mistakes*10)}render()}
function reset(){state=fresh();r.bottleMolecules.innerHTML="";$$('.flying-molecule,.flying-scoop').forEach(el=>el.remove());r.complete.classList.remove("show");r.complete.setAttribute("aria-hidden","true");render()}
$$('.method').forEach(b=>b.addEventListener('click',()=>chooseMethod(b.dataset.method)));$$('.flavor').forEach(b=>b.addEventListener('click',()=>chooseFlavor(b.dataset.flavor)));$$('.mineral-btn').forEach(b=>b.addEventListener('click',()=>addMineral(b.dataset.mineral,b)));r.bottle.addEventListener('click',toggleLid);r.water.addEventListener('click',addWater);r.powder.addEventListener('click',addPowder);r.shake.addEventListener('click',shake);r.bottle.addEventListener('pointerdown',e=>pointerStart=e.clientX);r.bottle.addEventListener('pointerup',e=>{if(pointerStart!==undefined&&Math.abs(e.clientX-pointerStart)>45&&state.sealed){suppressClick=true;shake()}pointerStart=undefined});$('#reset-btn').addEventListener('click',reset);$('#mix-another').addEventListener('click',reset);$('#help-btn').addEventListener('click',()=>r.help.showModal());$('#close-help').addEventListener('click',()=>r.help.close());r.help.addEventListener('click',e=>{if(e.target===r.help)r.help.close()});reset();
